/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.IT;

import Business.UserAccount.UserAccount;
import Business.Validate;
import Business.WorkQueue.SupportWorkRequest;
import UserInterface.UserAccountManagement.ObservingTextField;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jiya
 */
public class ProcessMyRequestITJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessMyRequestITJPanel
     */
    JPanel userProcessContainer;
     UserAccount userAccount;
     SupportWorkRequest swr;
     int wfh;
    public ProcessMyRequestITJPanel(JPanel userProcessContainer, UserAccount userAccount, SupportWorkRequest swr,int wfh) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        this.swr=swr;
        this.wfh = wfh;
        
        txtTicket.setText(String.valueOf(swr.getTicketNumber()));
        taComment.setText(swr.getComments());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblswan = new javax.swing.JLabel();
        lblTicketNumber = new javax.swing.JLabel();
        lblFirstName2 = new javax.swing.JLabel();
        txtTicket = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taComment = new javax.swing.JTextArea();
        btnUpdatePatientProfile = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        lblswan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblswan.setForeground(new java.awt.Color(255, 255, 255));
        lblswan.setText("Ticket Details");
        add(lblswan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 230, 50));

        lblTicketNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTicketNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblTicketNumber.setText("<html>Ticket Number <font color = red>*</font></html>");
        add(lblTicketNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        lblFirstName2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFirstName2.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName2.setText("<html>Comment  <font color = red>*</font></html>");
        add(lblFirstName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        txtTicket.setEnabled(false);
        add(txtTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 170, 30));

        taComment.setColumns(20);
        taComment.setRows(5);
        taComment.setEnabled(false);
        jScrollPane1.setViewportView(taComment);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, 170, -1));

        btnUpdatePatientProfile.setBackground(new java.awt.Color(255, 102, 102));
        btnUpdatePatientProfile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdatePatientProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdatePatientProfile.setText("Update Patient Profile");
        btnUpdatePatientProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdatePatientProfileActionPerformed(evt);
            }
        });
        add(btnUpdatePatientProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        btnReturn.setBackground(new java.awt.Color(255, 102, 102));
        btnReturn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(255, 255, 255));
        btnReturn.setText("Return Ticket");
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });
        add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cl = (CardLayout) userProcessContainer.getLayout();
        cl.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdatePatientProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdatePatientProfileActionPerformed
        // TODO add your handling code here:
        if(wfh==1)
            {
                Validate.createLogFile(userAccount.getUsername(), "Employee viewed patient details");
            }
          ViewUpdatePatientDetailsJPanel viewUpdatePatientDetailsJPanel = new ViewUpdatePatientDetailsJPanel(userProcessContainer,swr,wfh);
        userProcessContainer.add("ViewUpdatePatientDetailsJPanel",viewUpdatePatientDetailsJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
        
    }//GEN-LAST:event_btnUpdatePatientProfileActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
     if(wfh==1)
            {
                Validate.createLogFile(userAccount.getUsername(), "Employee returned the ticket");
            }
           
            swr.setStatus("Returned");
           swr.setSwrReturnStatus("Returned");
       
            JOptionPane.showMessageDialog(null,"WorkRequest returned","Error",JOptionPane.ERROR_MESSAGE);
        
    }//GEN-LAST:event_btnReturnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnUpdatePatientProfile;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFirstName2;
    private javax.swing.JLabel lblTicketNumber;
    private javax.swing.JLabel lblswan;
    private javax.swing.JTextArea taComment;
    private javax.swing.JTextField txtTicket;
    // End of variables declaration//GEN-END:variables
}
