/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.IT;

import Business.UserAccount.UserAccount;
import Business.Validate;
import Business.WorkQueue.SupportWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jiya
 */
public class ServeMyWorkRequestITJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ServeMyWorkRequestITJPanel
     */
     JPanel userProcessContainer;
     UserAccount userAccount;
     SimpleDateFormat sdf;
     int wfh;
    public ServeMyWorkRequestITJPanel(JPanel userProcessContainer, UserAccount userAccount,int wfh) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.wfh = wfh;
      sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss a");
        populateTable();
    }
    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblITTickets.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
             if(request instanceof SupportWorkRequest)
           {
            Object[] row = new Object[6];
            row[0] = request.getTicketNumber();
            row[1] = request;
            row[2] = ((SupportWorkRequest) request).getAssignedby() == null? null :((SupportWorkRequest) request).getAssignedby().getEmployee();
            row[3] = sdf.format(request.getRequestDate());
            row[4] = ((SupportWorkRequest) request).getResolveDate() == null? null :sdf.format(((SupportWorkRequest) request).getResolveDate());
            
            row[5] = ((SupportWorkRequest) request).getSwrReturnStatus() == null ? request.getStatus():((SupportWorkRequest) request).getSwrReturnStatus();
            
           
           
           
            model.addRow(row);
           
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblswan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblITTickets = new javax.swing.JTable();
        btnProcess = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        lblswan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblswan.setForeground(new java.awt.Color(255, 255, 255));
        lblswan.setText("My Tickets");
        add(lblswan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 230, 50));

        tblITTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket Number", "Message", "Sender", "Requested Date", "Resolved Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblITTickets);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 840, 260));

        btnProcess.setBackground(new java.awt.Color(255, 102, 102));
        btnProcess.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProcess.setForeground(new java.awt.Color(255, 255, 255));
        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 150, -1));

        btnRefresh.setBackground(new java.awt.Color(255, 102, 102));
        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefresh.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 90, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cl = (CardLayout) userProcessContainer.getLayout();
        cl.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblITTickets.getSelectedRow();
        if(selectedRow <0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row","Info",1);
            return;
        }
        SupportWorkRequest request = (SupportWorkRequest) tblITTickets.getValueAt(selectedRow, 1);
        if(request.getSwrReturnStatus()!= null)
        {
            if(request.getSwrReturnStatus().equalsIgnoreCase("Returned"))
            {
                JOptionPane.showMessageDialog(null,"Request is returned Cannot process");
            }
             else
        {
            if(wfh==1)
            {
                Validate.createLogFile(userAccount.getUsername(), "Employee Working on ticket");
            }
        ProcessMyRequestITJPanel processMyRequestITJPanel = new ProcessMyRequestITJPanel(userProcessContainer,userAccount, request,wfh);
        userProcessContainer.add("ProcessMyRequestITJPanel",processMyRequestITJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
        }
        }
        else
        {
            if(wfh==1)
            {
                Validate.createLogFile(userAccount.getUsername(), "Employee working on ticket");
            }
        ProcessMyRequestITJPanel processMyRequestITJPanel = new ProcessMyRequestITJPanel(userProcessContainer,userAccount, request,wfh);
        userProcessContainer.add("ProcessMyRequestITJPanel",processMyRequestITJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblswan;
    private javax.swing.JTable tblITTickets;
    // End of variables declaration//GEN-END:variables
}
