/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.IT;

import Business.Organization.ITOrganization;
import Business.UserAccount.UserAccount;
import Business.Validate;
import Business.WorkQueue.SupportWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jiya
 */
public class ServeITWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ServeITWorkRequestJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    ITOrganization organization;
    SimpleDateFormat sdf;
    int wfh;
    public ServeITWorkRequestJPanel(JPanel userProcessContainer, UserAccount userAccoount, ITOrganization organization,int wfh) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccoount;
        this.organization = organization;
        this.wfh=wfh;
        sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss a");
        populateTable();
    }
    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblITWrokRequest.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()){
           
            Object[] row = new Object[7];
            row[0] = request.getTicketNumber();
            row[1] = request;
            row[2] = ((SupportWorkRequest) request).getAssignedby() == null? null :((SupportWorkRequest) request).getAssignedby().getEmployee();
            row[3] = sdf.format(request.getRequestDate());
            row[4] = ((SupportWorkRequest) request).getPatient() == null? null :((SupportWorkRequest) request).getPatient();
            row[5] = ((SupportWorkRequest) request).getEmployeeReceiver() == null? null :((SupportWorkRequest) request).getEmployeeReceiver().getEmployee();
            row[6] = ((SupportWorkRequest) request).getSwrReturnStatus() == null ? request.getStatus():((SupportWorkRequest) request).getSwrReturnStatus();
            
           
           
           
            model.addRow(row);
           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblswan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblITWrokRequest = new javax.swing.JTable();
        btnAssignToMe2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        lblswan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblswan.setForeground(new java.awt.Color(255, 255, 255));
        lblswan.setText("Tickets");
        add(lblswan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 230, 50));

        tblITWrokRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket Number", "Message", "Sender", "Requested Date", "Patient", "Receiver", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblITWrokRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 760, 260));

        btnAssignToMe2.setBackground(new java.awt.Color(255, 102, 102));
        btnAssignToMe2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAssignToMe2.setForeground(new java.awt.Color(255, 255, 255));
        btnAssignToMe2.setText("Assign To Me");
        btnAssignToMe2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignToMe2ActionPerformed(evt);
            }
        });
        add(btnAssignToMe2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cl = (CardLayout) userProcessContainer.getLayout();
        cl.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignToMe2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignToMe2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblITWrokRequest.getSelectedRow();

        if (selectedRow < 0){
            return;
        }

        SupportWorkRequest request = (SupportWorkRequest)tblITWrokRequest.getValueAt(selectedRow, 1);
       
        
          String status = (String)tblITWrokRequest.getValueAt(selectedRow, 6);
        
        if(status.equalsIgnoreCase("Pending Request"))
        {
            if(wfh==1)
            {
                Validate.createLogFile(userAccount.getUsername(), "Employee assigned Ticket to himself");
            }
        
             request.setEmployeeReceiver(userAccount);
            request.setStatus("Work in Progress");
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            populateTable();
            
        }
        else
        {
           JOptionPane.showMessageDialog(null,"WorkRequest already assigned","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAssignToMe2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignToMe2;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblswan;
    private javax.swing.JTable tblITWrokRequest;
    // End of variables declaration//GEN-END:variables
}
