/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Nurse;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import Business.Person.Patient;
import Business.Person.PatientDirectory;
import Business.Validate;
import UserInterface.Reports.PatientsVitalReportJPanel;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jiya
 */
public class ServePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ServePatientJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
     PatientDirectory patientDirectory;
    public ServePatientJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        
        populateTable();
    }
    public void populateTable()
    {
         DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();
       
        model.setRowCount(0);
        for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(o instanceof PatientOrganization)
            { 
                patientDirectory = o.getPatientDirectory();
                for (Patient p: o.getPatientDirectory().getpatientList()){
                Object[] row = new Object[3];
                row[0] = p.getPatientId();
                 row[1] = p;
            
                    if(p.isIsSurveyTaken())
                        row[2] = "Yes";
                    else
                        row[2] ="No";


                    model.addRow(row);
            }
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblswan = new javax.swing.JLabel();
        btnClaimBills = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        btnInsuranceDetails = new javax.swing.JButton();
        btnSurvey = new javax.swing.JButton();
        btnVitals = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnVitalTrend = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        lblswan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblswan.setForeground(new java.awt.Color(255, 255, 255));
        lblswan.setText("Serve Patient");
        add(lblswan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 230, 50));

        btnClaimBills.setBackground(new java.awt.Color(255, 102, 102));
        btnClaimBills.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClaimBills.setForeground(new java.awt.Color(255, 255, 255));
        btnClaimBills.setText("Claim Bills");
        btnClaimBills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClaimBillsActionPerformed(evt);
            }
        });
        add(btnClaimBills, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 140, -1));

        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Patient Name", "Survey Taken?"
            }
        ));
        jScrollPane1.setViewportView(tblPatient);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 90, 560, 170));

        btnInsuranceDetails.setBackground(new java.awt.Color(255, 102, 102));
        btnInsuranceDetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnInsuranceDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnInsuranceDetails.setText("View Insurance Details");
        btnInsuranceDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsuranceDetailsActionPerformed(evt);
            }
        });
        add(btnInsuranceDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 190, -1));

        btnSurvey.setBackground(new java.awt.Color(255, 102, 102));
        btnSurvey.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSurvey.setForeground(new java.awt.Color(255, 255, 255));
        btnSurvey.setText("Survey");
        btnSurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSurveyActionPerformed(evt);
            }
        });
        add(btnSurvey, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 190, -1));

        btnVitals.setBackground(new java.awt.Color(255, 102, 102));
        btnVitals.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVitals.setForeground(new java.awt.Color(255, 255, 255));
        btnVitals.setText("Vital Signs");
        btnVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitalsActionPerformed(evt);
            }
        });
        add(btnVitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 140, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Search by Patient ID");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));
        add(txtPatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 100, 30));

        btnSearch.setBackground(new java.awt.Color(255, 102, 102));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 480, -1, 30));

        btnVitalTrend.setBackground(new java.awt.Color(255, 102, 102));
        btnVitalTrend.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVitalTrend.setForeground(new java.awt.Color(255, 255, 255));
        btnVitalTrend.setText("View Vitals Trends");
        btnVitalTrend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitalTrendActionPerformed(evt);
            }
        });
        add(btnVitalTrend, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cl = (CardLayout) userProcessContainer.getLayout();
        cl.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnClaimBillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClaimBillsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPatient.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row","Information",1);
            return;
        }
        Patient p = (Patient) tblPatient.getValueAt(selectedRow, 1);
        PatientClaimDetailsJPanel patientClaimPanel = new PatientClaimDetailsJPanel(userProcessContainer,p);
        userProcessContainer.add("PatientClaimDetailsJPanel",patientClaimPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnClaimBillsActionPerformed

    private void btnInsuranceDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsuranceDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPatient.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row","Information",1);
            return;
        }
        Patient p = (Patient) tblPatient.getValueAt(selectedRow, 1);
        ViewInsuranceDetailsJPanel patientInsurance = new ViewInsuranceDetailsJPanel(userProcessContainer,p);
        userProcessContainer.add("ViewInsuranceDetailsJPanel",patientInsurance);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnInsuranceDetailsActionPerformed

    private void btnSurveyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSurveyActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPatient.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row","Information",1);
            return;
        }
        Patient p = (Patient) tblPatient.getValueAt(selectedRow, 1);
         PatientSurveyJPanel patientSurvey = new PatientSurveyJPanel(userProcessContainer,p);
        userProcessContainer.add("PatientSurveyJPanel",patientSurvey);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnSurveyActionPerformed

    private void btnVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitalsActionPerformed
        // TODO add your handling code here:
           int selectedRow = tblPatient.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row","Information",1);
            return;
        }
        Patient p = (Patient) tblPatient.getValueAt(selectedRow, 1);
        ViewPatientVitalsJPanel viewVital = new ViewPatientVitalsJPanel(userProcessContainer,p);
        userProcessContainer.add("ViewPatientVitalsJPanel",viewVital);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
        
    }//GEN-LAST:event_btnVitalsActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String patientId = txtPatientID.getText().trim();
        if(patientId.isEmpty())
        {
            populateTable();
        }
        else
        {
            boolean boolpatientId = Validate.isNumeric(patientId);
            if(boolpatientId)
            {
                DefaultTableModel model = (DefaultTableModel) tblPatient.getModel();

                        model.setRowCount(0);
                txtPatientID.setBackground(Color.WHITE);
                txtPatientID.setText("");
                for(Patient p : patientDirectory.getpatientList())
                {
                    if(p.getPatientId() == Integer.parseInt(patientId))
                    {
                        

                        Object[] row = new Object[3];
                        row[0] = p.getPatientId();
                        row[1] = p;

                        if(p.isIsSurveyTaken())
                        row[2] = "Yes";
                        else
                        row[2] ="No";

                        model.addRow(row);
                    }
                }
            }
            else
            {
                txtPatientID.setBackground(Color.red);
                JOptionPane.showMessageDialog(null,"Invalid data","Error",JOptionPane.ERROR_MESSAGE);
                System.out.println("error num" + JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnVitalTrendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitalTrendActionPerformed
        // TODO add your handling code here:
           int selectedRow = tblPatient.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row","Information",1);
            return;
        }
        Patient p = (Patient) tblPatient.getValueAt(selectedRow, 1);
        PatientsVitalReportJPanel patientsnurseVitalReportJPanel = new PatientsVitalReportJPanel(userProcessContainer,p);
        userProcessContainer.add("PatientsVitalReportJPanel",patientsnurseVitalReportJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnVitalTrendActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClaimBills;
    private javax.swing.JButton btnInsuranceDetails;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSurvey;
    private javax.swing.JButton btnVitalTrend;
    private javax.swing.JButton btnVitals;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblswan;
    private javax.swing.JTable tblPatient;
    private javax.swing.JTextField txtPatientID;
    // End of variables declaration//GEN-END:variables
}
