/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Billing;

import Business.Enterprise.Enterprise;
import Business.Organization.BillingOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Validate;
import UserInterface.UserAccountManagement.TimesheetJPanel;
import UserInterface.UserAccountManagement.ViewUpdatePersonDetailsJPanel;
import UserInterface.UserAccountManagement.WorkFromHomeRequestJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Jiya
 */
public class BillingWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BillingWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    BillingOrganization organization;
    Enterprise enterprise;
    int wfh;
    public BillingWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, BillingOrganization organization, Enterprise enterprise,int wfh) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.organization = organization;
        this.wfh = wfh;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnWorkRequest = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnMyWorkRequest = new javax.swing.JButton();
        btnTmeSheet = new javax.swing.JButton();
        btnWFHRequest = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Billing WorkArea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 170, 40));

        btnWorkRequest.setBackground(new java.awt.Color(0, 204, 204));
        btnWorkRequest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnWorkRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnWorkRequest.setText("<html><Center><h3>Serve</h3><h3> WorkRequest</h3><Center><html>");
        btnWorkRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkRequestActionPerformed(evt);
            }
        });
        add(btnWorkRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 140, 109));

        btnProfile.setBackground(new java.awt.Color(0, 51, 204));
        btnProfile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setText("<html><Center><h3>Update</h3><h3>Profile</h3><Center><html>");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 280, 110));

        btnMyWorkRequest.setBackground(new java.awt.Color(255, 153, 0));
        btnMyWorkRequest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnMyWorkRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnMyWorkRequest.setText("<html><Center><h3>Serve</h3><h3>My  WorkRequest</h3><Center><html>");
        btnMyWorkRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyWorkRequestActionPerformed(evt);
            }
        });
        add(btnMyWorkRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 140, 109));

        btnTmeSheet.setBackground(new java.awt.Color(255, 153, 153));
        btnTmeSheet.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnTmeSheet.setForeground(new java.awt.Color(255, 255, 255));
        btnTmeSheet.setText("<html><Center><h3>Timesheet</h3><Center><html>");
        btnTmeSheet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTmeSheetActionPerformed(evt);
            }
        });
        add(btnTmeSheet, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 140, 109));

        btnWFHRequest.setBackground(new java.awt.Color(51, 153, 0));
        btnWFHRequest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnWFHRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnWFHRequest.setText("<html><Center><h3>Work From Home</h3><h3> WorkRequest</h3><Center><html>");
        btnWFHRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWFHRequestActionPerformed(evt);
            }
        });
        add(btnWFHRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 140, 109));
    }// </editor-fold>//GEN-END:initComponents

    private void btnWorkRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkRequestActionPerformed
        // TODO add your handling code here:
        if(wfh==1)
            {
                Validate.createLogFile(userAccount.getUsername(), "Employee viewed workrequest");
            }
        ServeBillingWorkRequestJPanel serveBillingWorkRequestJPanel = new ServeBillingWorkRequestJPanel(userProcessContainer,userAccount,organization,wfh);
        userProcessContainer.add("ServeBillingWorkRequestJPanel",serveBillingWorkRequestJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnWorkRequestActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        if(wfh==1)
            {
                Validate.createLogFile(userAccount.getUsername(), "Employee updated his profile");
            }
        ViewUpdatePersonDetailsJPanel viewUpdateNurse = new ViewUpdatePersonDetailsJPanel(userProcessContainer,userAccount.getEmployee(), userAccount,"employee","edit",wfh);
        userProcessContainer.add("ViewUpdatePersonDetailsJPanel",viewUpdateNurse);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnMyWorkRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyWorkRequestActionPerformed
        // TODO add your handling code here:
        if(wfh==1)
            {
                Validate.createLogFile(userAccount.getUsername(), "Employee viewed his workrequest");
            }
        ServeMyWorkRequestBillingJPanel serveMyWorkRequestBillingJPanel = new ServeMyWorkRequestBillingJPanel(userProcessContainer,userAccount,wfh);
        userProcessContainer.add("serveMyWorkRequestBillingJPanel",serveMyWorkRequestBillingJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnMyWorkRequestActionPerformed

    private void btnTmeSheetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTmeSheetActionPerformed
        // TODO add your handling code here:
        TimesheetJPanel timesheetBillingJPanel = new TimesheetJPanel(userProcessContainer,userAccount,wfh);
        userProcessContainer.add("TimesheetBillingJPanel",timesheetBillingJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnTmeSheetActionPerformed

    private void btnWFHRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWFHRequestActionPerformed
        // TODO add your handling code here:
          WorkFromHomeRequestJPanel workFromHomeITRequestJPanel = new WorkFromHomeRequestJPanel( userProcessContainer,  userAccount,  enterprise);
        userProcessContainer.add("WorkFromHomeRequestITJPanel",workFromHomeITRequestJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnWFHRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMyWorkRequest;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnTmeSheet;
    private javax.swing.JButton btnWFHRequest;
    private javax.swing.JButton btnWorkRequest;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
