/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Validate;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jiya
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    EcoSystem system;
    SimpleDateFormat sdf;
    public ManageEnterpriseJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
            this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss a");
        AddEnterpriseJPanel.setVisible(false);
        populateTable();
        populateCombo();
    }
    public void populateCombo()
    {
        cmbNetwork.removeAllItems();
        cmbEnterpriseType.removeAllItems();

        for (Network network : system.getNetworkList()) {
            cmbNetwork.addItem(network);
        }

        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            cmbEnterpriseType.addItem(type);
        }
    }
    public void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel)tblEnterprise.getModel();
        dtm.setRowCount(0);
        for(Network nw: system.getNetworkList())
        {
            for(Enterprise e: nw.getEnterpriseDirectory().getEnterpriseList())
            {
                Object row[] = new Object[6];
                row[0]= e.getEnterpriseType();
                row[1] = nw;
                row[2] = e;
                row[3] = e.getLocation();
                row[4] = sdf.format(e.getCreatedOn());
                if(e.getModifiedOn() == null)
                {
                    row[5] = "";
                }
                else
                {
                    row[5] = sdf.format(e.getModifiedOn());
                }
                dtm.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEnterprise = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnview = new javax.swing.JButton();
        AddEnterpriseJPanel = new javax.swing.JPanel();
        lblAddEnterprise = new javax.swing.JLabel();
        lblNetworkName = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnUpdateSave = new javax.swing.JButton();
        cmbNetwork = new javax.swing.JComboBox();
        lblNetworkName1 = new javax.swing.JLabel();
        txtEnterpriseName = new javax.swing.JTextField();
        lblNetworkName2 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        cmbEnterpriseType = new javax.swing.JComboBox();
        lblEnterpriseType = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage EnterPrise");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, 40));

        tblEnterprise.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Type", "Network Name", "Enterprise Name", "Location", "Created On", "Modified On"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEnterprise);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 80, 760, 110));

        btnDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Enterprise");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 150, -1));

        btnAdd.setBackground(new java.awt.Color(255, 102, 102));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add Enterprise");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, -1, -1));

        btnview.setBackground(new java.awt.Color(255, 102, 102));
        btnview.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnview.setForeground(new java.awt.Color(255, 255, 255));
        btnview.setText("View Enterprise Details");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });
        add(btnview, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        AddEnterpriseJPanel.setOpaque(false);
        AddEnterpriseJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddEnterprise.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddEnterprise.setForeground(new java.awt.Color(255, 255, 255));
        lblAddEnterprise.setText("Enterprise Details");
        AddEnterpriseJPanel.add(lblAddEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 110, -1));

        lblNetworkName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNetworkName.setForeground(new java.awt.Color(255, 255, 255));
        lblNetworkName.setText("<html>Network Name <font color = red>*</font></html>");
        AddEnterpriseJPanel.add(lblNetworkName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        btnSave.setBackground(new java.awt.Color(255, 102, 102));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        AddEnterpriseJPanel.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(255, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Edit");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        AddEnterpriseJPanel.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 60, -1));

        btnUpdateSave.setBackground(new java.awt.Color(255, 102, 102));
        btnUpdateSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateSave.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateSave.setText("Save");
        btnUpdateSave.setEnabled(false);
        btnUpdateSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSaveActionPerformed(evt);
            }
        });
        AddEnterpriseJPanel.add(btnUpdateSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));

        AddEnterpriseJPanel.add(cmbNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 160, 30));

        lblNetworkName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNetworkName1.setForeground(new java.awt.Color(255, 255, 255));
        lblNetworkName1.setText("<html>Enterprise Name <font color = red>*</font></html>");
        AddEnterpriseJPanel.add(lblNetworkName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 30));

        txtEnterpriseName.setEnabled(false);
        AddEnterpriseJPanel.add(txtEnterpriseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 160, 30));

        lblNetworkName2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNetworkName2.setForeground(new java.awt.Color(255, 255, 255));
        lblNetworkName2.setText("<html>Location <font color = red>*</font></html>");
        AddEnterpriseJPanel.add(lblNetworkName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 30));

        txtLocation.setEnabled(false);
        AddEnterpriseJPanel.add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 160, 30));

        AddEnterpriseJPanel.add(cmbEnterpriseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 160, 30));

        lblEnterpriseType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEnterpriseType.setForeground(new java.awt.Color(255, 255, 255));
        lblEnterpriseType.setText("<html>Enterprise Type <font color = red>*</font></html>");
        AddEnterpriseJPanel.add(lblEnterpriseType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        add(AddEnterpriseJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 450, 300));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblEnterprise.getSelectedRow();
        if(selectedrow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row to edit","Information",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Network nw = (Network) tblEnterprise.getValueAt(selectedrow, 1);
        Enterprise e = (Enterprise) tblEnterprise.getValueAt(selectedrow, 2);
        nw.getEnterpriseDirectory().deleteEnterprise(e);
        JOptionPane.showMessageDialog(null,"Enterprise deleted successfully","Success",JOptionPane.INFORMATION_MESSAGE);
        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        AddEnterpriseJPanel.setVisible(true);
        txtEnterpriseName.setText("");
        txtLocation.setText("");
        btnUpdate.setVisible(false);
        btnUpdateSave.setVisible(false);
        populateCombo();
        cmbEnterpriseType.setEnabled(true);
        cmbNetwork.setEnabled(true);
        txtEnterpriseName.setEnabled(true);
        txtLocation.setEnabled(true);
        btnSave.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:

        int selectedrow = tblEnterprise.getSelectedRow();
        if(selectedrow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row to edit","Information",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Enterprise e = (Enterprise) tblEnterprise.getValueAt(selectedrow,2);
        Network nw = (Network) tblEnterprise.getValueAt(selectedrow,1);
        AddEnterpriseJPanel.setVisible(true);
        txtEnterpriseName.setEnabled(false);
        txtEnterpriseName.setText(e.getName());
        txtLocation.setEnabled(false);
        txtLocation.setText(e.getLocation());
        cmbNetwork.setSelectedItem(nw);
        cmbEnterpriseType.setSelectedItem(e.getEnterpriseType());
        
        cmbEnterpriseType.setEnabled(false);
        cmbNetwork.setEnabled(false);
        btnUpdate.setVisible(true);
        btnUpdate.setEnabled(true);
        btnSave.setVisible(false);
        btnUpdateSave.setVisible(true);
        btnUpdateSave.setEnabled(false);

    }//GEN-LAST:event_btnviewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        btnUpdate.setVisible(false);
        //Date date = new Date();
        String enterpriseName = txtEnterpriseName.getText().trim();
        String enterpriseLoc = txtLocation.getText().trim();
        boolean boolenterpriseName = Validate.isalphanumeric(enterpriseName);
        boolean boolenterpriseLc = Validate.isalphanumeric(enterpriseLoc);
        if(!enterpriseName.isEmpty() && !enterpriseLoc.isEmpty() && cmbEnterpriseType.getSelectedItem() != null && cmbNetwork.getSelectedItem() != null)
        {
            if(boolenterpriseName && boolenterpriseLc)
            {
                txtLocation.setBackground(Color.WHITE);
                txtEnterpriseName.setBackground(Color.WHITE);
                Network nw = (Network) cmbNetwork.getSelectedItem();
                Enterprise e = nw.getEnterpriseDirectory().createAndAddEnterprise(enterpriseName,(Enterprise.EnterpriseType) cmbEnterpriseType.getSelectedItem());     
                e.setCreatedOn(new Date());
                e.setLocation(enterpriseLoc);
            
                JOptionPane.showMessageDialog(null,"Enterprise added succesfully","Succes",JOptionPane.INFORMATION_MESSAGE);
                txtEnterpriseName.setText("");
                txtLocation.setText("");
                populateTable();
                AddEnterpriseJPanel.setVisible(false);
            }
            else
            {
                if(!boolenterpriseLc)
                {
                    txtLocation.setBackground(Color.red);
                    
                }
                if(!boolenterpriseName)
                {
                    txtEnterpriseName.setBackground(Color.red);
                }
                JOptionPane.showMessageDialog(null,"Invalid data","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Fields cannot be empty","Information",JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnUpdateSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        txtEnterpriseName.setEnabled(true);
        txtLocation.setEnabled(true);
        cmbEnterpriseType.setEnabled(false);
        cmbNetwork.setEnabled(false);

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUpdateSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSaveActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblEnterprise.getSelectedRow();
        
        Enterprise e = (Enterprise) tblEnterprise.getValueAt(selectedrow, 2);
        String enterpriseName = txtEnterpriseName.getText().trim();
        String enterpriseloc = txtLocation.getText().trim();
        String enterpriseLoc = txtLocation.getText().trim();
        boolean boolenterpriseName = Validate.isalphanumeric(enterpriseName);
        boolean boolenterpriseLc = Validate.isalphanumeric(enterpriseLoc);
        if(!enterpriseName.isEmpty() && !enterpriseloc.isEmpty())
        {
            if(boolenterpriseName && boolenterpriseLc)
            {
                txtLocation.setBackground(Color.WHITE);
                txtEnterpriseName.setBackground(Color.WHITE);
            
                e.setName(enterpriseName);
                e.setLocation(enterpriseloc);

                e.setModifiedOn(new Date());
                JOptionPane.showMessageDialog(null,"Enterprise details updated successfully","Success",JOptionPane.INFORMATION_MESSAGE);
                populateTable();
                AddEnterpriseJPanel.setVisible(false);
            }
            else
            {
                if(!boolenterpriseLc)
                {
                    txtLocation.setBackground(Color.red);
                    
                }
                if(!boolenterpriseName)
                {
                    txtEnterpriseName.setBackground(Color.red);
                }
                JOptionPane.showMessageDialog(null,"Invalid data","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Fields cannot be empty","Warning",2);
        }
    }//GEN-LAST:event_btnUpdateSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddEnterpriseJPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateSave;
    private javax.swing.JButton btnview;
    private javax.swing.JComboBox cmbEnterpriseType;
    private javax.swing.JComboBox cmbNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddEnterprise;
    private javax.swing.JLabel lblEnterpriseType;
    private javax.swing.JLabel lblNetworkName;
    private javax.swing.JLabel lblNetworkName1;
    private javax.swing.JLabel lblNetworkName2;
    private javax.swing.JTable tblEnterprise;
    private javax.swing.JTextField txtEnterpriseName;
    private javax.swing.JTextField txtLocation;
    // End of variables declaration//GEN-END:variables
}
