/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;


import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;



/**
 *
 * @author Jiya
 */
public class WorldMapSWANJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OfficeLocatorJPanel
     */
    
    JPanel userProcessContainer;
    public WorldMapSWANJPanel(JPanel userProcessContainer) {
       
        initComponents();
        
      this.userProcessContainer = userProcessContainer;

    }
   

     

      

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBoston = new javax.swing.JButton();
        btnIndia = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        lblworld = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(null);

        btnBoston.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Hospital.jpg"))); // NOI18N
        btnBoston.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBostonActionPerformed(evt);
            }
        });
        add(btnBoston);
        btnBoston.setBounds(270, 190, 50, 50);

        btnIndia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SupportCenter.jpg"))); // NOI18N
        btnIndia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndiaActionPerformed(evt);
            }
        });
        add(btnIndia);
        btnIndia.setBounds(880, 250, 40, 40);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 51));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 0));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jSeparator1.setOpaque(true);
        jSeparator1.setPreferredSize(new java.awt.Dimension(8, 8));
        add(jSeparator1);
        jSeparator1.setBounds(320, 190, 580, 10);

        jSeparator2.setBackground(new java.awt.Color(255, 255, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setOpaque(true);
        jSeparator2.setPreferredSize(new java.awt.Dimension(8, 15));
        add(jSeparator2);
        jSeparator2.setBounds(898, 200, 8, 50);

        lblworld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/WorldMap.jpg"))); // NOI18N
        lblworld.setText("ok");
        add(lblworld);
        lblworld.setBounds(90, 30, 940, 606);

        btnBack.setBackground(new java.awt.Color(0, 153, 153));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(0, 0, 50, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBostonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBostonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"SWAN Hospital \n Provides best healthcare facility in the world");
//        SystemAdminWorkAreaJPanel OrganizationStructurePanel = new SystemAdminWorkAreaJPanel(userProcessContainer);
//        userProcessContainer.add("OrganizationStructureJPanel",OrganizationStructurePanel);
//        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
//        cl.next(userProcessContainer);
        
    }//GEN-LAST:event_btnBostonActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnIndiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndiaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"SWAN Patient support \n Helping millions of patients with their day to day queries regarding phi, Insurance and claim information...");
    }//GEN-LAST:event_btnIndiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBoston;
    private javax.swing.JButton btnIndia;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblworld;
    // End of variables declaration//GEN-END:variables
}
