/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SOC;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.SOCOrganization;
import Business.UserAccount.UserAccount;
import UserInterface.SOC.Report.ApprovedTicketsJPanel;
import UserInterface.SOC.Report.ListOfIPActiveJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Jiya
 */
public class BIReportsSOCJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BIReportsJPanel
     */
       JPanel userProcessContainer;

    Enterprise enterprise;
    UserAccount userAccount;
    EcoSystem system;
    SOCOrganization organization;
    public BIReportsSOCJPanel(JPanel userProcessContainer, UserAccount userAccount,SOCOrganization organization,EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
   this.organization =organization;
   this.system = system;
   this.userAccount = userAccount;
        this.enterprise = enterprise;
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnApprovedTicket = new javax.swing.JButton();
        btnIP = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BI Reports");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, 40));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        btnApprovedTicket.setBackground(new java.awt.Color(204, 0, 204));
        btnApprovedTicket.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnApprovedTicket.setForeground(new java.awt.Color(255, 255, 255));
        btnApprovedTicket.setText("<html><Center><h3>Tickets</h3><h3>Approved</h3><Center><html>");
        btnApprovedTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprovedTicketActionPerformed(evt);
            }
        });
        add(btnApprovedTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 130, 100));

        btnIP.setBackground(new java.awt.Color(102, 204, 0));
        btnIP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIP.setForeground(new java.awt.Color(255, 255, 255));
        btnIP.setText("<html><Center><h3>Active</h3><h3>IP</h3><Center><html>");
        btnIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIPActionPerformed(evt);
            }
        });
        add(btnIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 130, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnApprovedTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprovedTicketActionPerformed
        // TODO add your handling code here:
                ApprovedTicketsJPanel approvedTicketsJPanel = new ApprovedTicketsJPanel(userProcessContainer,organization,userAccount);
        userProcessContainer.add("ApprovedTicketsJPanel",approvedTicketsJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnApprovedTicketActionPerformed

    private void btnIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIPActionPerformed
        // TODO add your handling code here:
         ListOfIPActiveJPanel listOfIPActiveJPanel = new ListOfIPActiveJPanel(userProcessContainer,system);
        userProcessContainer.add("ListOfIPActiveJPanel",listOfIPActiveJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnIPActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprovedTicket;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnIP;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
