/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EnterpriseAdmin.Reports;

import Business.DateUtils;
import Business.Enterprise.Enterprise;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.Organization.SupportAdminOrganization;
import Business.Person.Employee;
import Business.TimeSheet.TimeSheet;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jiya
 */
public class EmployeesNotFilledTimesheetEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HardWorkingEmployeesJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    SimpleDateFormat sdf;
    public EmployeesNotFilledTimesheetEnterpriseJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
                this.userProcessContainer = userProcessContainer;
                this.enterprise = enterprise;
                sdf = new SimpleDateFormat("dd/MM/yyyy");
                populateTable();
    }
    public void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) tblTimesheet.getModel();
        dtm.setRowCount(0);
        Date date = new Date();
         Object[] row = new Object[3];
        for(Organization o: enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(o instanceof AdminOrganization || o instanceof SupportAdminOrganization)
            {
                for(Employee e: o.getEmployeeDirectory().getEmployeeList())
                {
                    boolean flag = false;
                    for(TimeSheet ts : e.getTimeSheetDirectory().getTimesheetDirectory())
                    {
                         
                        if(DateUtils.isToday(ts.getToday()))
                        {
                           flag = true;
                           break; 
                        }
                    
                    }
                    if(flag)
                    {
                         
                             row[0] = sdf.format(date);
                            row[1]= e;
                             row[2] = "Yes";
                        dtm.addRow(row);
                    }
                    else
                    {
                             row[0] = sdf.format(date);
                            row[1]= e;
                             row[2] = "No";
                        dtm.addRow(row);
                    }
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTimesheet = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TimeSheet Status");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 320, 40));

        tblTimesheet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Employee", "Timesheet Filled"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTimesheet);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 230));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTimesheet;
    // End of variables declaration//GEN-END:variables
}
