/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.OrganizationAdmin;


import UserInterface.UserAccountManagement.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.Validate;
import Business.WorkQueue.PatientWorkRequest;
import Business.WorkQueue.WorkRequest;
import com.qt.datapicker.DatePicker;
import java.awt.CardLayout;
import java.awt.Color;
import java.net.InetAddress;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

import javax.swing.JPanel;



/**
 *
 * @author Jiya
 */
public class ViewRequestDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpJPanel
     */
    JPanel userProcessContainer;
    
    SimpleDateFormat sdf;
    WorkRequest request;
    String requestType;
    public ViewRequestDetailsJPanel(JPanel userProcessContainer, WorkRequest request, String requestType) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.request = request;
        this.requestType = requestType;
       sdf = new SimpleDateFormat("dd/MM/yyyy");
       populateForm();
      
    }
    public void populateForm()
    {
        if(requestType.equals("patient"))
        {
            PatientWorkRequest pr = (PatientWorkRequest) request;
            txtDOB.setText(sdf.format(pr.getDOB()));
            txtFirstName.setText(pr.getFirstName());
            txtIP.setText(pr.getIpAddress());
            txtLastName1.setText(pr.getLastName());
            txtPhone.setText(String.valueOf(pr.getPhone()));
            txtSSN.setText(pr.getSsn());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblswan = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblFirstName1 = new javax.swing.JLabel();
        lblFirstName2 = new javax.swing.JLabel();
        lblFirstName4 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtDOB = new ObservingTextField();
        txtPhone = new javax.swing.JTextField();
        txtLastName1 = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblssn = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        txtIP = new javax.swing.JTextField();
        lblssn1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblswan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblswan.setForeground(new java.awt.Color(255, 255, 255));
        lblswan.setText("Request Details");
        add(lblswan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 230, 50));

        lblPhone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPhone.setText("<html>Phone <font color = red>*</font></html>");
        add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, -1, 20));

        lblFirstName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFirstName1.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName1.setText("<html>First Name <font color = red>*</font></html>");
        add(lblFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, -1, -1));

        lblFirstName2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFirstName2.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName2.setText("<html>Last Name <font color = red>*</font></html>");
        add(lblFirstName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        lblFirstName4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFirstName4.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName4.setText("<html>Date of Birth <font color = red>*</font></html>");
        add(lblFirstName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, -1, 20));

        txtFirstName.setEnabled(false);
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 140, 30));

        txtDOB.setEnabled(false);
        add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 140, 30));

        txtPhone.setEnabled(false);
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 140, 30));

        txtLastName1.setEnabled(false);
        add(txtLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 140, 30));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        lblssn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblssn.setForeground(new java.awt.Color(255, 255, 255));
        lblssn.setText("<html>SSN <font color = red>*</font></html>");
        add(lblssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, 30));

        txtSSN.setEnabled(false);
        add(txtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 140, 30));

        txtIP.setEnabled(false);
        add(txtIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 140, 30));

        lblssn1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblssn1.setForeground(new java.awt.Color(255, 255, 255));
        lblssn1.setText("<html>IP <font color = red>*</font></html>");
        add(lblssn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
         CardLayout cl = (CardLayout) userProcessContainer.getLayout();
         cl.previous(userProcessContainer);
        

    
    }//GEN-LAST:event_btnBackActionPerformed
    private Locale getLocale(String lang) {
     
     if(lang !=null && lang.length() >0)
     {
         return new Locale(lang);
     }
     else
     {
         
             return Locale.US;
     }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblFirstName1;
    private javax.swing.JLabel lblFirstName2;
    private javax.swing.JLabel lblFirstName4;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lblssn1;
    private javax.swing.JLabel lblswan;
    private ObservingTextField txtDOB;
    /*
    private javax.swing.JTextField txtDOB;
    */
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtLastName1;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSSN;
    // End of variables declaration//GEN-END:variables

   
}
