/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Doctor;

import Business.Organization.DoctorOrganization;
import Business.UserAccount.UserAccount;
import Business.Validate;

import Business.WorkQueue.HospitalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jiya
 */
public class ServeMyWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ServeMyWorkRequestJPanel
     */
        JPanel userProcessContainer;
    UserAccount userAccount;
    DoctorOrganization organization;
    public ServeMyWorkRequestJPanel(JPanel userProcessContainer, UserAccount userAccount,DoctorOrganization organization) {
        initComponents();
           this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
         ProcessRequestJPanel.setVisible(false);
        txtDiagonosis.setBackground(Color.WHITE);
        populateTable();
    }
public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)tblDoctorWorkRequest.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            if(request.getStatus().equalsIgnoreCase("Cancelled"))
            {
            }
            else
            {
            Object[] row = new Object[6];
            row[0] = request;
            row[1] = ((HospitalWorkRequest) request).getNurseSender() == null ? null :((HospitalWorkRequest) request).getNurseSender().getEmployee();
            row[2] = ((HospitalWorkRequest) request).getDocreceiver() == null ? null : ((HospitalWorkRequest) request).getDocreceiver().getEmployee();
            row[3] = ((HospitalWorkRequest) request).getDiagonosis();
            row[4] = ((HospitalWorkRequest) request).getPatient();
            row[5] = request.getStatus();
            
            
            model.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblswan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoctorWorkRequest = new javax.swing.JTable();
        btnProcess = new javax.swing.JButton();
        ProcessRequestJPanel = new javax.swing.JPanel();
        lblAddOrganization2 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        lblRoomNumber = new javax.swing.JLabel();
        txtDiagonosis = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        lblswan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblswan.setForeground(new java.awt.Color(255, 255, 255));
        lblswan.setText("Serve My WorkRequest");
        add(lblswan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 230, 50));

        tblDoctorWorkRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Message", "Sender", "Receiver", "Diagonosis", "Patient", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDoctorWorkRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 990, 200));

        btnProcess.setBackground(new java.awt.Color(255, 102, 102));
        btnProcess.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnProcess.setForeground(new java.awt.Color(255, 255, 255));
        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });
        add(btnProcess, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 130, -1));

        ProcessRequestJPanel.setOpaque(false);
        ProcessRequestJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddOrganization2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddOrganization2.setForeground(new java.awt.Color(255, 255, 255));
        lblAddOrganization2.setText("Request Details");
        ProcessRequestJPanel.add(lblAddOrganization2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 140, -1));

        btnSave.setBackground(new java.awt.Color(255, 102, 102));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        ProcessRequestJPanel.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, -1, -1));

        lblRoomNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRoomNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblRoomNumber.setText("<html>Diagonosis <font color = red>*</font></html>");
        ProcessRequestJPanel.add(lblRoomNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));
        ProcessRequestJPanel.add(txtDiagonosis, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 160, 30));

        add(ProcessRequestJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 500, 240));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cl = (CardLayout) userProcessContainer.getLayout();
        cl.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDoctorWorkRequest.getSelectedRow();

        if (selectedRow < 0){
            return;
        }
        HospitalWorkRequest request = (HospitalWorkRequest)tblDoctorWorkRequest.getValueAt(selectedRow, 0);
        if(request.getDiagonosis() == null)
        {
            ProcessRequestJPanel.setVisible(true);
        }
        else
        {
            ProcessRequestJPanel.setVisible(false);
            JOptionPane.showMessageDialog(null,"Patient already diagonised","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnProcessActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int selectedRow = tblDoctorWorkRequest.getSelectedRow();
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please select any row","Info",1);
            return;
        }
        HospitalWorkRequest request = (HospitalWorkRequest)tblDoctorWorkRequest.getValueAt(selectedRow, 0);
        //Patient patient = (Patient) tblDoctorWorkRequest.getValueAt(selectedRow, 5);

        String diagonosis = txtDiagonosis.getText().trim();

        boolean boolroomNum = Validate.isalphanumeric(diagonosis);

        if(!diagonosis.isEmpty())
        {
            if(boolroomNum)
            {
                Date completedDate = new Date();
                txtDiagonosis.setBackground(Color.WHITE);
                request.setDiagonosis(diagonosis);
                request.setStatus("Completed");
                request.setResolveDate(completedDate);
                
                JOptionPane.showMessageDialog(null,"Patient treatment process completed sucessfully","Success",1);
                populateTable();
                txtDiagonosis.setText("");
                ProcessRequestJPanel.setVisible(false);

            }
            else
            {
                txtDiagonosis.setBackground(Color.red);
                JOptionPane.showMessageDialog(null,"Invalid Data","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Fields cannot be empty","Info",1);
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ProcessRequestJPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProcess;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddOrganization2;
    private javax.swing.JLabel lblRoomNumber;
    private javax.swing.JLabel lblswan;
    private javax.swing.JTable tblDoctorWorkRequest;
    private javax.swing.JTextField txtDiagonosis;
    // End of variables declaration//GEN-END:variables
}
