/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientSupport;

import Business.UserAccount.UserAccount;
import Business.Validate;
import Business.WorkQueue.SupportWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jiya
 */
public class ServeSupportMyWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ServeITWorkRequestJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    SimpleDateFormat sdf;
    int wfh;
    public ServeSupportMyWorkRequestJPanel(JPanel userProcessContainer,UserAccount userAccount,int wfh) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.wfh=wfh;
        sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss a");
         populateTable();
    }
    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblTicket.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
             if(request instanceof SupportWorkRequest)
           {
            Object[] row = new Object[6];
            row[0] = request.getTicketNumber();
            row[1] = request;
            row[2] = ((SupportWorkRequest) request).getSender() == null? null :((SupportWorkRequest) request).getSender().getPatient();
            row[3] = sdf.format(request.getRequestDate());
            row[4] = request.getStatus();
            row[5] = ((SupportWorkRequest) request).getOrganization();
           
           
           
            model.addRow(row);
           }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblswan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTicket = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        lblswan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblswan.setForeground(new java.awt.Color(255, 255, 255));
        lblswan.setText("My Tickets");
        add(lblswan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 230, 50));

        tblTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket Number", "Message", "Sender", "Requested Date", "Status", "Assigned Organization"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTicket);
        if (tblTicket.getColumnModel().getColumnCount() > 0) {
            tblTicket.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblTicket.getColumnModel().getColumn(2).setPreferredWidth(15);
            tblTicket.getColumnModel().getColumn(4).setPreferredWidth(20);
            tblTicket.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 1030, 260));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search Ticket");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 150, -1));
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 140, 30));

        btnSearch.setBackground(new java.awt.Color(255, 102, 102));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cl = (CardLayout) userProcessContainer.getLayout();
        cl.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchText = txtSearch.getText().trim();
        boolean boolsearch = Validate.isNumeric(searchText);
        if(!searchText.isEmpty())
        {
            if(boolsearch)
            {
                txtSearch.setBackground(Color.WHITE);
                DefaultTableModel model = (DefaultTableModel)tblTicket.getModel();

                model.setRowCount(0);
                for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList())
                {
                    if(request.getTicketNumber()== Integer.parseInt(searchText))
                    {
                        Object[] row = new Object[6];
                        row[0] = request.getTicketNumber();
                        row[1] = request;
                        row[2] = ((SupportWorkRequest) request).getSender() == null? null :((SupportWorkRequest) request).getSender().getPatient();
                        row[3] = sdf.format(request.getRequestDate());
                        row[4] = request.getStatus();
                        row[5] = ((SupportWorkRequest) request).getOrganization();
        
                          model.addRow(row);
                    }
                }
                txtSearch.setText("");
            }
            else
            {
                if(!boolsearch)
                {
                    txtSearch.setBackground(Color.red);
                }
                else
                txtSearch.setBackground(Color.WHITE);
            }

        }
        else
        {
            populateTable();
        }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblswan;
    private javax.swing.JTable tblTicket;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
