/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupportOrganizationAdmin;

import Business.Enterprise.Enterprise;
import UserInterface.SupportOrganizationAdmin.Report.SupportEmployeesNotFilledTimesheetJPanel;
import UserInterface.SupportOrganizationAdmin.Report.SupportHardWorkingEmployeesJPanel;
import UserInterface.SupportOrganizationAdmin.Report.SupportTicketsStatusJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Jiya
 */
public class BIReportsSupportOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BIReportsJPanel
     */
       JPanel userProcessContainer;

    Enterprise enterprise;
        
    public BIReportsSupportOrganizationJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
   
        this.enterprise = enterprise;
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnEmployeeCount = new javax.swing.JButton();
        btnticket = new javax.swing.JButton();
        btnEmployeeTimesheet1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BI Reports");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 130, 40));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        btnEmployeeCount.setBackground(new java.awt.Color(204, 0, 204));
        btnEmployeeCount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEmployeeCount.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployeeCount.setText("<html><Center><h3>Employee</h3><h3>Efficiency</h3><Center><html>");
        btnEmployeeCount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeCountActionPerformed(evt);
            }
        });
        add(btnEmployeeCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 130, 100));

        btnticket.setBackground(new java.awt.Color(255, 102, 102));
        btnticket.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnticket.setForeground(new java.awt.Color(255, 255, 255));
        btnticket.setText("<html><Center><h3>Tickets</h3><h3>Status</h3><Center><html>");
        btnticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnticketActionPerformed(evt);
            }
        });
        add(btnticket, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 130, 200));

        btnEmployeeTimesheet1.setBackground(new java.awt.Color(102, 204, 0));
        btnEmployeeTimesheet1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEmployeeTimesheet1.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployeeTimesheet1.setText("<html><Center><h3>Employees</h3><h3>Not Filled Timesheet</h3><Center><html>");
        btnEmployeeTimesheet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeTimesheet1ActionPerformed(evt);
            }
        });
        add(btnEmployeeTimesheet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 130, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEmployeeCountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeCountActionPerformed
        // TODO add your handling code here:
                SupportHardWorkingEmployeesJPanel supportHardWorkingEmployeesJPanel = new SupportHardWorkingEmployeesJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("SupportHardWorkingEmployeesJPanel",supportHardWorkingEmployeesJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnEmployeeCountActionPerformed

    private void btnticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnticketActionPerformed
        // TODO add your handling code here:
         SupportTicketsStatusJPanel supportTicketsStatusJPanel = new SupportTicketsStatusJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("SupportTicketsStatusJPanel",supportTicketsStatusJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnticketActionPerformed

    private void btnEmployeeTimesheet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeTimesheet1ActionPerformed
        // TODO add your handling code here:
         SupportEmployeesNotFilledTimesheetJPanel supportEmployeesNotFilledTimesheetJPanel = new SupportEmployeesNotFilledTimesheetJPanel(userProcessContainer,enterprise);
        userProcessContainer.add("SupportEmployeesNotFilledTimesheetJPanel",supportEmployeesNotFilledTimesheetJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnEmployeeTimesheet1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEmployeeCount;
    private javax.swing.JButton btnEmployeeTimesheet1;
    private javax.swing.JButton btnticket;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
