/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupportOrganizationAdmin;


import Business.UserAccount.UserAccount;
import Business.Validate;

import Business.WorkQueue.WorkFromHomeWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;

import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jiya
 */
public class ManageSupportAdminMyWorkRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageWorkRequestJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
 
    public ManageSupportAdminMyWorkRequestJPanel(JPanel userProcessContainer,UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
      
       
       populateTable();
    }
    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel)tblAdminWorkrequest.getModel();
        
        model.setRowCount(0);
         
        for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
          
            Object[] row = new Object[5];
            row[0] = request.getTicketNumber();
            row[1] = ((WorkFromHomeWorkRequest)request).getRequest();
            
            row[2] = request.getSender().getEmployee();
           
            row[3] = request;
            row[4] = request.getStatus();
           
            model.addRow(row);
         
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdminWorkrequest = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage WorkRequest");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 170, 40));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        tblAdminWorkrequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket Number", "Request", "Sender", "Message", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAdminWorkrequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 730, 270));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search Ticket");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 150, -1));

        btnSearch.setBackground(new java.awt.Color(255, 102, 102));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, -1, 30));
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchText = txtSearch.getText().trim();
        boolean boolsearch = Validate.isNumeric(searchText);
        if(!searchText.isEmpty())
        {
            if(boolsearch)
            {
                txtSearch.setBackground(Color.WHITE);
                DefaultTableModel model = (DefaultTableModel)tblAdminWorkrequest.getModel();
        
                 model.setRowCount(0);
                for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList())
                {
                    if(request.getTicketNumber()== Integer.parseInt(searchText))
                    {
                        Object[] row = new Object[5];
                        row[0] = request.getTicketNumber();
                        row[1] = ((WorkFromHomeWorkRequest)request).getRequest();

                        row[2] = request.getSender().getEmployee();

                        row[3] = request;
                        row[4] = request.getStatus();

                        model.addRow(row);
                    }
                }
                txtSearch.setText("");
            }
            else
            {
                if(!boolsearch)
                {
                    txtSearch.setBackground(Color.red);
                }
                else
                    txtSearch.setBackground(Color.WHITE);
            }
            
        }
        else
        {
            populateTable();
        }
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblAdminWorkrequest;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
