/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.SupportOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SupportWorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jiya
 */
public class CreateTicketJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateTicketJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    EcoSystem system;
    SimpleDateFormat sdf;
    public CreateTicketJPanel(JPanel userProcessCOntainer, UserAccount userAccount, EcoSystem system) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessCOntainer;
        this.system = system;
        sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss a");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack1 = new javax.swing.JButton();
        lblVitalDetails = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        cmbQueryType = new javax.swing.JComboBox<>();
        lblQueryType1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taMessage = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        lblVitalDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVitalDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblVitalDetails.setText("Create Ticket");
        add(lblVitalDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 230, 50));

        lblMessage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblMessage.setForeground(new java.awt.Color(255, 255, 255));
        lblMessage.setText("<html>Message <font color=red>*</color></html>");
        add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 130, 30));

        cmbQueryType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<--Select-->", "PHI Update", "Billing Update", "Policy Update" }));
        add(cmbQueryType, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 310, 30));

        lblQueryType1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblQueryType1.setForeground(new java.awt.Color(255, 255, 255));
        lblQueryType1.setText("<html>Select Ticket Type <font color=red>*</color></html>");
        add(lblQueryType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 130, 30));

        taMessage.setColumns(20);
        taMessage.setRows(5);
        jScrollPane1.setViewportView(taMessage);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 310, 150));

        btnSubmit.setBackground(new java.awt.Color(255, 102, 102));
        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Call      1(800) 000-0000");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cl = (CardLayout) userProcessContainer.getLayout();
        cl.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        int queryType = cmbQueryType.getSelectedIndex();
        String message = taMessage.getText();
        Date date = new Date();
        String date1 = sdf.format(date);
        try{
        if(cmbQueryType.getSelectedIndex() !=0 && !message.isEmpty())
        {
            SupportWorkRequest swr = new SupportWorkRequest();
            swr.setComments(message);
            swr.setMessage((String)cmbQueryType.getSelectedItem());
            swr.setSender(userAccount);
            swr.setRequestDate(sdf.parse(date1));
            swr.setStatus("Open");
            swr.setPatient(userAccount.getPatient());
            swr.setQueryType(queryType);
             Organization org = null;
            for(Network nw : system.getNetworkList())
            {
                for(Enterprise e : nw.getEnterpriseDirectory().getEnterpriseList())
                {
                    for(Organization o: e.getOrganizationDirectory().getOrganizationList())
                    {
                         if(o instanceof SupportOrganization)
                        {
                        
                                
                                     org = o;
                                      break;
                                
                        }
                      
                    }
                }
            }
             if (org!=null){
                org.getWorkQueue().getWorkRequestList().add(swr);
               userAccount.getWorkQueue().getWorkRequestList().add(swr);
                System.out.println("Doctor organization"+org.getWorkQueue().getWorkRequestList().size());
                 JOptionPane.showMessageDialog(null,"Ticket raised successfully","Success",1);
                 taMessage.setText("");
                 cmbQueryType.setSelectedIndex(0);
              
            }
        }
        }catch(Exception e)
        {
            
        }
    }//GEN-LAST:event_btnSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> cmbQueryType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblQueryType1;
    private javax.swing.JLabel lblVitalDetails;
    private javax.swing.JTextArea taMessage;
    // End of variables declaration//GEN-END:variables
}
