/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.UserAccount.UserAccount;
import Business.WorkQueue.HospitalWorkRequest;
import Business.WorkQueue.SupportWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jiya
 */
public class PatientMyTicketsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientMyTicketsJPanel
     */
        JPanel userProcessContainer;
    UserAccount userAccount;
    SimpleDateFormat sdf;
    public PatientMyTicketsJPanel(JPanel userProcessContainer, UserAccount userAccount) {
        initComponents();
          this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss a");
      populateTable();
    }
    public void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblTicket.getModel();
        System.out.println("request"+userAccount.getWorkQueue().getWorkRequestList().size());
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
           
            Object[] row = new Object[6];
            row[0] = request.getTicketNumber();
            row[1] = request;
            row[2] = sdf.format(request.getRequestDate());
            row[3] = ((SupportWorkRequest) request).getEmployeeReceiver() == null? null :((SupportWorkRequest) request).getEmployeeReceiver().getEmployee();
            row[4] = request.getResolveDate()== null? null :sdf.format(request.getResolveDate());
           
            row[5] = request.getStatus()== null ? "Open" :request.getStatus();
           
           
            model.addRow(row);
           
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack1 = new javax.swing.JButton();
        lblVitalDetails = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTicket = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        lblVitalDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVitalDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblVitalDetails.setText("Ticket Details");
        add(lblVitalDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 230, 50));

        tblTicket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket Number", "Message", "Created On", "Resolved By", "Resolved On", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTicket);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 780, 370));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cl = (CardLayout) userProcessContainer.getLayout();
        cl.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVitalDetails;
    private javax.swing.JTable tblTicket;
    // End of variables declaration//GEN-END:variables
}
