/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.EcoSystem;
import Business.Organization.PatientOrganization;
import Business.UserAccount.UserAccount;
import UserInterface.Receptionist.ReceptionistWorkRequestJPanel;
import UserInterface.UserAccountManagement.ViewUpdatePersonDetailsJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Jiya
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    PatientOrganization organization;
    EcoSystem system;
    public PatientWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, PatientOrganization organization, EcoSystem system,int wfh) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.organization = organization;
        this.system = system;
       // userAccount.getWorkQueue().getWorkRequestList().clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnViewInsuranceDetails = new javax.swing.JButton();
        btnViewClaims = new javax.swing.JButton();
        btnWorkRequest = new javax.swing.JButton();
        btnViewVitals = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnViewMyRequest = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PatientWorkArea");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 170, 40));

        btnViewInsuranceDetails.setBackground(new java.awt.Color(204, 51, 255));
        btnViewInsuranceDetails.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewInsuranceDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnViewInsuranceDetails.setText("<html><Center><h3>View</h3><h3>Insurance Details</h3><Center><html>");
        btnViewInsuranceDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewInsuranceDetailsActionPerformed(evt);
            }
        });
        add(btnViewInsuranceDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 89, 137, 110));

        btnViewClaims.setBackground(new java.awt.Color(255, 204, 102));
        btnViewClaims.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewClaims.setForeground(new java.awt.Color(255, 255, 255));
        btnViewClaims.setText("<html><Center><h3>View</h3><h3>Claims</h3><Center><html>");
        btnViewClaims.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewClaimsActionPerformed(evt);
            }
        });
        add(btnViewClaims, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 140, 109));

        btnWorkRequest.setBackground(new java.awt.Color(0, 204, 204));
        btnWorkRequest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnWorkRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnWorkRequest.setText("<html><Center><h3>Customer</h3><h3> Support</h3><Center><html>");
        btnWorkRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkRequestActionPerformed(evt);
            }
        });
        add(btnWorkRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 140, 330));

        btnViewVitals.setBackground(new java.awt.Color(255, 153, 153));
        btnViewVitals.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewVitals.setForeground(new java.awt.Color(255, 255, 255));
        btnViewVitals.setText("<html><Center><h3>View</h3><h3>Vital Details</h3><Center><html>");
        btnViewVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVitalsActionPerformed(evt);
            }
        });
        add(btnViewVitals, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 140, 109));

        btnProfile.setBackground(new java.awt.Color(0, 51, 204));
        btnProfile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(255, 255, 255));
        btnProfile.setText("<html><Center><h3>Update</h3><h3>Profile</h3><Center><html>");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });
        add(btnProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 280, 110));

        btnViewMyRequest.setBackground(new java.awt.Color(51, 153, 0));
        btnViewMyRequest.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewMyRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnViewMyRequest.setText("<html><Center><h3>My</h3><h3> Tickets</h3><Center><html>");
        btnViewMyRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMyRequestActionPerformed(evt);
            }
        });
        add(btnViewMyRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 140, 109));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewInsuranceDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewInsuranceDetailsActionPerformed
        // TODO add your handling code here:

        ViewInsuranceDetailsJPanel viewPatientInsuJPanelrance = new ViewInsuranceDetailsJPanel(userProcessContainer,userAccount.getPatient().getInsurancePolicyDirectory());
        userProcessContainer.add("ViewInsuranceDetailsJPanel",viewPatientInsuJPanelrance);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnViewInsuranceDetailsActionPerformed

    private void btnViewClaimsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewClaimsActionPerformed
        // TODO add your handling code here:
        ViewClaimDetailsJPanel viewPatientClaimDetailsJPanel = new ViewClaimDetailsJPanel(userProcessContainer,userAccount.getPatient().getClaimDirectory());
        userProcessContainer.add("ViewClaimDetailsJPanel",viewPatientClaimDetailsJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnViewClaimsActionPerformed

    private void btnWorkRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkRequestActionPerformed
        // TODO add your handling code here:
        CreateTicketJPanel createPatientSupportTicketJPanel = new CreateTicketJPanel(userProcessContainer,userAccount,system);
        userProcessContainer.add("CreateTicketJPanel",createPatientSupportTicketJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnWorkRequestActionPerformed

    private void btnViewVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVitalsActionPerformed
        // TODO add your handling code here:
         ViewVitalDetailsJPanel viewPatientVitalDetailsJPanel = new ViewVitalDetailsJPanel(userProcessContainer,userAccount.getPatient().getVitalSignHistory());
        userProcessContainer.add("ViewVitalDetailsJPanel",viewPatientVitalDetailsJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnViewVitalsActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        ViewUpdatePersonDetailsJPanel viewUpdateNurse = new ViewUpdatePersonDetailsJPanel(userProcessContainer,userAccount.getPatient(),userAccount, "patient","edit",0);
        userProcessContainer.add("ViewUpdatePersonDetailsJPanel",viewUpdateNurse);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnViewMyRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMyRequestActionPerformed
        // TODO add your handling code here:
         PatientMyTicketsJPanel patientMyTicketsJPanel = new PatientMyTicketsJPanel(userProcessContainer,userAccount);
        userProcessContainer.add("PatientMyTicketsJPanel",patientMyTicketsJPanel);
        CardLayout cl = (CardLayout)userProcessContainer.getLayout();
        cl.next(userProcessContainer);
        
    }//GEN-LAST:event_btnViewMyRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnViewClaims;
    private javax.swing.JButton btnViewInsuranceDetails;
    private javax.swing.JButton btnViewMyRequest;
    private javax.swing.JButton btnViewVitals;
    private javax.swing.JButton btnWorkRequest;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
