/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.Vitals.Vital;
import Business.Vitals.VitalHistory;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Jiya
 */
public class ViewVitalDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewVitalDetailsJPanel
     */
    JPanel userProcessContainer;
    VitalHistory vitalHistory;
    SimpleDateFormat sdf;
    public ViewVitalDetailsJPanel(JPanel userProcessContainer,VitalHistory vitalHistory) {
        initComponents();
    this.userProcessContainer = userProcessContainer;
       this.vitalHistory = vitalHistory;
        sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss a");
       
       AddVitalPanel.setVisible(false);
       VitalJPanel.setVisible(false);
        populateTable();
        
    }
   
    public void populateTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) tblVitalHistory.getModel();
        dtm.setRowCount(0);
        for(Vital v: vitalHistory.getVitalSignHistory())
        {
            Object row[] = new Object[2];
            row[0] = sdf.format(v.getCurrDate());
            row[1] = v;
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack1 = new javax.swing.JButton();
        lblVitalDetails = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVitalHistory = new javax.swing.JTable();
        btnViewReport = new javax.swing.JButton();
        AddVitalPanel = new javax.swing.JPanel();
        lblAddOrganization2 = new javax.swing.JLabel();
        lblRespRate = new javax.swing.JLabel();
        lblHeartRate = new javax.swing.JLabel();
        lblBP = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblPounds = new javax.swing.JLabel();
        txtRespRate = new javax.swing.JTextField();
        txtBP = new javax.swing.JTextField();
        txtHeartRate = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        VitalJPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        lblVitalDetails.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblVitalDetails.setForeground(new java.awt.Color(255, 255, 255));
        lblVitalDetails.setText("Vital Details");
        add(lblVitalDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 230, 50));

        tblVitalHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Report Date", "Report Status"
            }
        ));
        jScrollPane1.setViewportView(tblVitalHistory);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 500, 120));

        btnViewReport.setBackground(new java.awt.Color(255, 102, 102));
        btnViewReport.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewReport.setForeground(new java.awt.Color(255, 255, 255));
        btnViewReport.setText("View Vital Detail");
        btnViewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReportActionPerformed(evt);
            }
        });
        add(btnViewReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        AddVitalPanel.setOpaque(false);
        AddVitalPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddOrganization2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddOrganization2.setForeground(new java.awt.Color(255, 255, 255));
        lblAddOrganization2.setText("Vital Details");
        AddVitalPanel.add(lblAddOrganization2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 140, -1));

        lblRespRate.setForeground(new java.awt.Color(255, 255, 255));
        lblRespRate.setText("Respiratory Rate");
        AddVitalPanel.add(lblRespRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 110, 10));

        lblHeartRate.setForeground(new java.awt.Color(255, 255, 255));
        lblHeartRate.setText("Heart Rate");
        AddVitalPanel.add(lblHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 80, 10));

        lblBP.setForeground(new java.awt.Color(255, 255, 255));
        lblBP.setText("Systolic Blood Pressure");
        AddVitalPanel.add(lblBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 140, 10));

        lblWeight.setForeground(new java.awt.Color(255, 255, 255));
        lblWeight.setText("Weight");
        AddVitalPanel.add(lblWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 60, 10));

        lblPounds.setForeground(new java.awt.Color(255, 255, 255));
        lblPounds.setText("Pounds");
        AddVitalPanel.add(lblPounds, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 60, 10));

        txtRespRate.setEnabled(false);
        AddVitalPanel.add(txtRespRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 140, 30));

        txtBP.setEnabled(false);
        AddVitalPanel.add(txtBP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 140, 30));

        txtHeartRate.setEnabled(false);
        AddVitalPanel.add(txtHeartRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 140, 30));

        txtWeight.setEnabled(false);
        AddVitalPanel.add(txtWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 140, 30));

        add(AddVitalPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 440, 340));

        VitalJPanel.setOpaque(false);
        VitalJPanel.setLayout(new java.awt.BorderLayout());
        add(VitalJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 260, 460, 340));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cl = (CardLayout) userProcessContainer.getLayout();
        cl.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void btnViewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportActionPerformed
        //View vital history retrive Vital details of selected row in JTable
        int selectedRow = tblVitalHistory.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null,"Select any row","Warning",1);
            return;
        }

        Vital vital = (Vital)tblVitalHistory.getValueAt(selectedRow,1);
        AddVitalPanel.setVisible(true);
       VitalJPanel.setVisible(true);
       
        txtBP.setText(String.valueOf(vital.getSysBP()));
        txtHeartRate.setText(String.valueOf(vital.getHeartRate()));
        txtRespRate.setText(String.valueOf(vital.getRespRate()));
        txtWeight.setText(String.valueOf(vital.getWeight()));
        populateChart(vital);
    }//GEN-LAST:event_btnViewReportActionPerformed
 public void populateChart(Vital v)
    {
        DefaultCategoryDataset bChart;
         bChart = new DefaultCategoryDataset();
          bChart.setValue(v.getSysBP(), "Vital Sign", "BP");
            bChart.setValue(v.getHeartRate(), "Vital Sign", "Heart Rate" );
            bChart.setValue(v.getRespRate(), "Vital Sign", "Resp Rate");
            bChart.setValue(v.getWeight(), "Vital Sign", "Weight");
             JFreeChart barChart = ChartFactory.createBarChart("Vital Signs","","", bChart,PlotOrientation.VERTICAL,true,true,false);
        CategoryPlot catChart = barChart.getCategoryPlot();
        BarRenderer b = (BarRenderer)catChart.getRenderer();
        b.setMaximumBarWidth(0.10);
        
        catChart.setRangeGridlinePaint(Color.WHITE);
        ChartPanel barPanel = new ChartPanel(barChart);
        
        VitalJPanel.removeAll();
        VitalJPanel.add(barPanel,BorderLayout.CENTER);
        VitalJPanel.validate();
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddVitalPanel;
    private javax.swing.JPanel VitalJPanel;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnViewReport;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddOrganization2;
    private javax.swing.JLabel lblBP;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblPounds;
    private javax.swing.JLabel lblRespRate;
    private javax.swing.JLabel lblVitalDetails;
    private javax.swing.JLabel lblWeight;
    private javax.swing.JTable tblVitalHistory;
    private javax.swing.JTextField txtBP;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtRespRate;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables
}
