/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Patient;

import Business.PersonInsurance.InsurancePolicy;
import Business.PersonInsurance.InsurancePolicyDirectory;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jiya
 */
public class ViewInsuranceDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewInsuranceDetailsJPanel
     */
    JPanel userProcessContainer;
    InsurancePolicyDirectory insuranceDirectory;
    SimpleDateFormat sdf;
    public ViewInsuranceDetailsJPanel(JPanel userProcessContainer, InsurancePolicyDirectory insuranceDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.insuranceDirectory = insuranceDirectory;
           AddInsurancePanel.setVisible(false);
            sdf = new SimpleDateFormat("dd/MM/yyyy");
            populateTable();
    }
    public void populateTable()
    {
         DefaultTableModel model = (DefaultTableModel) tblInsurance.getModel();
       
        model.setRowCount(0);
        for(InsurancePolicy ip : insuranceDirectory.getInsurancePolicyDirectory())
        {
           
                Object[] row = new Object[4];
                row[0] = ip;
                 row[1] = ip.getPolicyName();
                 row[2] = sdf.format(ip.getEffectiveDate());
                 if(ip.isIsActive())
                 {
                    row[3] = "Active";
                 }
                 else
                    row[3] = "InActive"; 

                    model.addRow(row);
            }
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblInsurance = new javax.swing.JTable();
        lblswan = new javax.swing.JLabel();
        btnView = new javax.swing.JButton();
        AddInsurancePanel = new javax.swing.JPanel();
        lblAddOrganization2 = new javax.swing.JLabel();
        lblPolicyName = new javax.swing.JLabel();
        txtEffectiveDate = new javax.swing.JTextField();
        lblInsuranceId = new javax.swing.JLabel();
        lblGroupNumber = new javax.swing.JLabel();
        txtGroupNumber = new javax.swing.JTextField();
        lblPolicyNumber = new javax.swing.JLabel();
        txtInsuranceID = new javax.swing.JTextField();
        lblOrganizationType1 = new javax.swing.JLabel();
        txtPolicyType = new javax.swing.JTextField();
        lblEffectiveDate = new javax.swing.JLabel();
        txtPolicyNumber = new javax.swing.JTextField();
        txtPolicyName1 = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblInsurance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Policy Number", "Policy Name", "Effective Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblInsurance);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 80, 620, 130));

        lblswan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblswan.setForeground(new java.awt.Color(255, 255, 255));
        lblswan.setText("Insurance Details");
        add(lblswan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 230, 50));

        btnView.setBackground(new java.awt.Color(255, 102, 102));
        btnView.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setText("View Insurance");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 140, -1));

        AddInsurancePanel.setOpaque(false);
        AddInsurancePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddOrganization2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddOrganization2.setForeground(new java.awt.Color(255, 255, 255));
        lblAddOrganization2.setText("Insurance Details");
        AddInsurancePanel.add(lblAddOrganization2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 140, -1));

        lblPolicyName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPolicyName.setForeground(new java.awt.Color(255, 255, 255));
        lblPolicyName.setText("<html>Policy Name <font color = red>*</font></html>");
        AddInsurancePanel.add(lblPolicyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, 30));

        txtEffectiveDate.setEnabled(false);
        AddInsurancePanel.add(txtEffectiveDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 160, 30));

        lblInsuranceId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblInsuranceId.setForeground(new java.awt.Color(255, 255, 255));
        lblInsuranceId.setText("<html>Insurance ID <font color = red>*</font></html>");
        AddInsurancePanel.add(lblInsuranceId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        lblGroupNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGroupNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblGroupNumber.setText("<html>Group Number <font color = red>*</font></html>");
        AddInsurancePanel.add(lblGroupNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 30));

        txtGroupNumber.setEnabled(false);
        AddInsurancePanel.add(txtGroupNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 160, 30));

        lblPolicyNumber.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPolicyNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblPolicyNumber.setText("<html>Policy Number <font color = red>*</font></html>");
        AddInsurancePanel.add(lblPolicyNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, 30));

        txtInsuranceID.setEnabled(false);
        AddInsurancePanel.add(txtInsuranceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 160, 30));

        lblOrganizationType1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOrganizationType1.setForeground(new java.awt.Color(255, 255, 255));
        lblOrganizationType1.setText("<html>Policy Type  <font color = red>*</font></html>");
        AddInsurancePanel.add(lblOrganizationType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        txtPolicyType.setEnabled(false);
        AddInsurancePanel.add(txtPolicyType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 160, 30));

        lblEffectiveDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEffectiveDate.setForeground(new java.awt.Color(255, 255, 255));
        lblEffectiveDate.setText("<html>Effective Date <font color = red>*</font></html>");
        AddInsurancePanel.add(lblEffectiveDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        txtPolicyNumber.setEnabled(false);
        AddInsurancePanel.add(txtPolicyNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 160, 30));

        txtPolicyName1.setEnabled(false);
        AddInsurancePanel.add(txtPolicyName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 160, 30));

        add(AddInsurancePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 500, 340));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed

        int selectedRow = tblInsurance.getSelectedRow();
        if(selectedRow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row","Information",1);
            return;
        }
        InsurancePolicy ip = (InsurancePolicy) tblInsurance.getValueAt(selectedRow, 0);
        AddInsurancePanel.setVisible(true);
    
       
        txtPolicyType.setText(ip.getPolicyNumber());
        txtInsuranceID.setText(String.valueOf(ip.getInsuranceId()));
        txtGroupNumber.setText(ip.getGroupNumber());
        txtEffectiveDate.setText(ip.getPolicyName());
        txtPolicyType.setText(ip.getInsuranceType().getValue());
        txtPolicyNumber.setText(ip.getPolicyNumber());
        txtPolicyName1.setText(ip.getPolicyName());
        txtEffectiveDate.setText(sdf.format(ip.getEffectiveDate()));
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cl = (CardLayout) userProcessContainer.getLayout();
        cl.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddInsurancePanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddOrganization2;
    private javax.swing.JLabel lblEffectiveDate;
    private javax.swing.JLabel lblGroupNumber;
    private javax.swing.JLabel lblInsuranceId;
    private javax.swing.JLabel lblOrganizationType1;
    private javax.swing.JLabel lblPolicyName;
    private javax.swing.JLabel lblPolicyNumber;
    private javax.swing.JLabel lblswan;
    private javax.swing.JTable tblInsurance;
    private javax.swing.JTextField txtEffectiveDate;
    private javax.swing.JTextField txtGroupNumber;
    private javax.swing.JTextField txtInsuranceID;
    private javax.swing.JTextField txtPolicyName1;
    private javax.swing.JTextField txtPolicyNumber;
    private javax.swing.JTextField txtPolicyType;
    // End of variables declaration//GEN-END:variables
}
