/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.UserAccountManagement;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jiya
 */
public class FirstTimeLoginJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FirstTimeLoginJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    Organization organization;
    Enterprise enterprise;
    EcoSystem business;
    int wfh;
    public FirstTimeLoginJPanel(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise, EcoSystem business,int wfh) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.business=business;
        this.wfh = wfh;
      //  System.out.println("name" + account.getUsername()+ account.getRole());
        if(userAccount.isFirstTimeLogin())
        {
       //     System.out.println("hi123");
            cmbSecurityQuestion.setEnabled(true);
            
        }
        else
        {
         //   System.out.println("hi");
            cmbSecurityQuestion.setSelectedIndex(userAccount.getSecurityQuestion() );
            cmbSecurityQuestion.setEnabled(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblswan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbSecurityQuestion = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtSecurityAnswer = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblswan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblswan.setForeground(new java.awt.Color(255, 255, 255));
        lblswan.setText("Access GateWay");
        add(lblswan, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 0, 142, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Security Question");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 149, 109, 22));

        cmbSecurityQuestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<--Select-->", "What is your pet's name?", "What is your favourite color?", "What is your best friend's name?" }));
        add(cmbSecurityQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 150, 262, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("<html>Answer <font color=red>*</font></html>");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 189, 109, 23));
        add(txtSecurityAnswer, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 192, 262, -1));

        btnSave.setBackground(new java.awt.Color(255, 102, 102));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Proceed");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 247, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String answer = txtSecurityAnswer.getText().trim();
        if(userAccount.isFirstTimeLogin())
        {
            if(cmbSecurityQuestion.getSelectedIndex() !=0 && !answer.isEmpty())
            {
                userAccount.setSecurityQuestion(cmbSecurityQuestion.getSelectedIndex());
                userAccount.setSecurityAnswer(answer);
                userAccount.setFirstTimeLogin(false);
                CardLayout cl = (CardLayout) userProcessContainer.getLayout();
                userProcessContainer.add("WorkArea",userAccount.getRole().createWorkArea(userProcessContainer, userAccount, organization, enterprise, business,wfh));
                cl.next(userProcessContainer);
            }
             else
            {
                JOptionPane.showMessageDialog(null,"Fields cannot be empty","Information",1);
            }
        }
        else
        {
            if(answer.equalsIgnoreCase(userAccount.getSecurityAnswer()))
            {
                 CardLayout cl = (CardLayout) userProcessContainer.getLayout();
                userProcessContainer.add("WorkArea",userAccount.getRole().createWorkArea(userProcessContainer, userAccount, organization, enterprise, business,wfh));
                cl.next(userProcessContainer);
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"Incorrect Response","Warning",2);
            }
            
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbSecurityQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblswan;
    private javax.swing.JTextField txtSecurityAnswer;
    // End of variables declaration//GEN-END:variables
}
