/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.UserAccountManagement;

import Business.DateUtils;
import Business.TimeSheet.TimeSheet;
import Business.UserAccount.UserAccount;
import Business.Validate;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jiya
 */
public class TimesheetJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TimesheetJPanel
     */
    JPanel userProcessContainer;
    UserAccount userAccount;
    SimpleDateFormat sdf;
    int wfhmain;
    public TimesheetJPanel(JPanel userProcessContainer, UserAccount userAccount,int wfh) {
        initComponents();
        this.userAccount = userAccount;
        this.userProcessContainer = userProcessContainer;
        sdf= new SimpleDateFormat("dd/MM/yyyy");
        this.wfhmain=wfh;
        populateTable();
        AddTimeSheetJPanel.setVisible(false);
        if(wfh==0)
        {
            chkWFH.setEnabled(false);
        }
        else
            chkWFH.setEnabled(true);
    }
    public void populateTable()
    {
        
        DefaultTableModel dtm = (DefaultTableModel)tblTimeSheet.getModel();
        dtm.setRowCount(0);
        boolean daypresent = false;
        for(TimeSheet ts : userAccount.getEmployee().getTimeSheetDirectory().getTimesheetDirectory())
        {
            daypresent = false;
            Object[] row = new Object[4];
            if(DateUtils.isToday(ts.getToday()))
            {
                daypresent = true;
            }
            row[0] = sdf.format(ts.getToday());
            if(ts.isPresent())
            {
                row[1] = "Present";
            }
            else
            {
                row[1] = "Absent";
            }
            row[2] = ts;
            if(ts.isWFH())
            {
                row[3] = "Yes";
            }
            else
            {
                row[3] = "No";
            }
            dtm.addRow(row);
            
        }
        if(daypresent)
        {
            btnAdd.setVisible(false);
        }
        else
        {
            btnAdd.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblswan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTimeSheet = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        AddTimeSheetJPanel = new javax.swing.JPanel();
        lblAddNetwork = new javax.swing.JLabel();
        lblpresent = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        chkPresent = new javax.swing.JCheckBox();
        lblDuration = new javax.swing.JLabel();
        chkWFH = new javax.swing.JCheckBox();
        lblWFH = new javax.swing.JLabel();
        txtDuration = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        lblswan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblswan.setForeground(new java.awt.Color(255, 255, 255));
        lblswan.setText("Timesheet");
        add(lblswan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 230, 50));

        tblTimeSheet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Present", "Duration", "Work From Home"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTimeSheet);
        if (tblTimeSheet.getColumnModel().getColumnCount() > 0) {
            tblTimeSheet.getColumnModel().getColumn(0).setPreferredWidth(75);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 81, 568, 137));

        btnAdd.setBackground(new java.awt.Color(255, 102, 102));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add TimeSheet");
        btnAdd.setToolTipText("");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        AddTimeSheetJPanel.setOpaque(false);
        AddTimeSheetJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddNetwork.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddNetwork.setForeground(new java.awt.Color(255, 255, 255));
        lblAddNetwork.setText("TimeSheet Details");
        AddTimeSheetJPanel.add(lblAddNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 110, -1));

        lblpresent.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblpresent.setForeground(new java.awt.Color(255, 255, 255));
        lblpresent.setText("Present");
        AddTimeSheetJPanel.add(lblpresent, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, 20));

        btnSave.setBackground(new java.awt.Color(255, 102, 102));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        AddTimeSheetJPanel.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        chkPresent.setOpaque(false);
        AddTimeSheetJPanel.add(chkPresent, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));

        lblDuration.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblDuration.setForeground(new java.awt.Color(255, 255, 255));
        lblDuration.setText("<html>Duration <font color = red>*</font></html>");
        AddTimeSheetJPanel.add(lblDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 70, 20));

        chkWFH.setOpaque(false);
        AddTimeSheetJPanel.add(chkWFH, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));

        lblWFH.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblWFH.setForeground(new java.awt.Color(255, 255, 255));
        lblWFH.setText("Work From Home");
        AddTimeSheetJPanel.add(lblWFH, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 120, 20));
        AddTimeSheetJPanel.add(txtDuration, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 70, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("hours");
        AddTimeSheetJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, -1, 20));

        add(AddTimeSheetJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 450, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout cl = (CardLayout) userProcessContainer.getLayout();
        cl.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
      try
      {
        Date date = new Date();
        String date1 = sdf.format(date);
        String duration = txtDuration.getText().trim();
        boolean present = false;
        boolean wfh = false;
        if(chkPresent.isSelected())
        {
            present = true;
        }
        if(chkWFH.isSelected())
        {
            wfh = true;
        }
        if(!duration.isEmpty())
        {
            if(Validate.isNumeric(duration))
            {
                if(Integer.parseInt(duration) <= 20)
                {
                        if(wfhmain==1 && wfh==false)
                        {
                            JOptionPane.showMessageDialog(null,"You have not selected Work from home","Error",JOptionPane.ERROR_MESSAGE);
                            return;
                        }
                        txtDuration.setBackground(Color.WHITE);
                        TimeSheet ts = userAccount.getEmployee().getTimeSheetDirectory().fillTimesheet();
                        ts.setDuration(Integer.parseInt(duration));
                        ts.setPresent(present);
                        ts.setWFH(wfh);
                        ts.setToday(sdf.parse(date1));
                        JOptionPane.showMessageDialog(null,"TimeSheet added succesfully","Succes",JOptionPane.INFORMATION_MESSAGE);
                        txtDuration.setText("");
                        chkPresent.setSelected(false);
                        chkWFH.setSelected(false);
                        populateTable();
                        AddTimeSheetJPanel.setVisible(false);
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Duration Cannot be greater than 20","Warning",1);
                   
                            
                }
            }
            else
            {
                txtDuration.setBackground(Color.red);
                JOptionPane.showMessageDialog(null,"Invalid data","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Fields cannot be empty","Information",JOptionPane.INFORMATION_MESSAGE);

        }
      }
      catch(Exception e)
      {
          System.out.println("Error date");
      }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
            AddTimeSheetJPanel.setVisible(true);
            txtDuration.setText("");
        chkPresent.setSelected(false);
        chkWFH.setSelected(false);
        
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddTimeSheetJPanel;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkPresent;
    private javax.swing.JCheckBox chkWFH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddNetwork;
    private javax.swing.JLabel lblDuration;
    private javax.swing.JLabel lblWFH;
    private javax.swing.JLabel lblpresent;
    private javax.swing.JLabel lblswan;
    private javax.swing.JTable tblTimeSheet;
    private javax.swing.JTextField txtDuration;
    // End of variables declaration//GEN-END:variables
}
