/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.UserAccountManagement;


import UserInterface.EnterpriseAdmin.*;
import UserInterface.UserAccountManagement.*;
import Business.Organization.Organization;

import Business.Person.Employee;
import Business.Person.Patient;
import Business.Person.Person;
import Business.Validate;
import UserInterface.EnterpriseAdmin.ViewEmployeeDirectoryJPanel;
import com.qt.datapicker.DatePicker;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

import javax.swing.JPanel;



/**
 *
 * @author Jiya
 */
public class ViewPersonDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SignUpJPanel
     */
    JPanel userProcessContainer;
    Employee employee;
    Patient patient;
    SimpleDateFormat sdf;
    String persontype;
    public ViewPersonDetailsJPanel(JPanel userProcessContainer, Person p, String persontype, String mode) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.persontype = persontype;
        sdf = new SimpleDateFormat("dd/MM/yyyy");
        System.out.println("in sign up panel");
       
        if(persontype.equals("employee"))
        {
            this.employee = (Employee) p;
              populateForm();
              
        }
        else
        {
            this.patient = (Patient) p;
            populatePatientForm();
        }
       
       
    
    }
    public void populateForm()
    {
       
        txtFirstName.setText(employee.getFirstName());
        txtLastName1.setText(employee.getLastName());
        txtAddress.setText(employee.getAddress());
        txtDOB.setText(sdf.format(employee.getDOB()));
        txtEmail.setText(employee.getEmail());
        txtLocation.setText(employee.getLocation());
        txtPhone.setText(String.valueOf(employee.getPhone()));
        txtSSN.setText(employee.getSsn());
        
            lblhireDate.setVisible(true);
            txthireDate.setVisible(true);
            
            txthireDate.setText(sdf.format(employee.getHireDate()));
        
        if(employee.getGender().equals("Male"))
        {
            radMale.setSelected(true);
            radFemale.setSelected(false);
        }
        else
        {
            radMale.setSelected(false);
            radFemale.setSelected(true);
        }
        if(employee.isMaritalStatus())
        {
            chkMarried.setSelected(true);
        }
        else
        {
            chkMarried.setSelected(false);
        }
        
    }
    public void populatePatientForm()
    {
        txtFirstName.setText(patient.getFirstName());
        txtLastName1.setText(patient.getLastName());
        txtAddress.setText(patient.getAddress());
        txtDOB.setText(sdf.format(patient.getDOB()));
        txtEmail.setText(patient.getEmail());
        txtLocation.setText(patient.getLocation());
        txtPhone.setText(String.valueOf(patient.getPhone()));
        txtSSN.setText(patient.getSsn());
        
            lblhireDate.setVisible(false);
            txthireDate.setVisible(false);
        
        if(patient.getGender().equals("Male"))
        {
            radMale.setSelected(true);
            radFemale.setSelected(false);
        }
        else
        {
            radMale.setSelected(false);
            radFemale.setSelected(true);
        }
        if(patient.isMaritalStatus())
        {
            chkMarried.setSelected(true);
        }
        else
        {
            chkMarried.setSelected(false);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblswan = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblFirstName1 = new javax.swing.JLabel();
        lblFirstName2 = new javax.swing.JLabel();
        lblFirstName3 = new javax.swing.JLabel();
        lblFirstName4 = new javax.swing.JLabel();
        lblFirstName5 = new javax.swing.JLabel();
        radMale = new javax.swing.JRadioButton();
        radFemale = new javax.swing.JRadioButton();
        txtPhone = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtDOB = new ObservingTextField();
        txtEmail = new javax.swing.JTextField();
        txtLastName1 = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblFirstName7 = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        lblMaritalstatus = new javax.swing.JLabel();
        lblssn = new javax.swing.JLabel();
        txtSSN = new javax.swing.JTextField();
        lblPicture = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        chkMarried = new javax.swing.JCheckBox();
        lblhireDate = new javax.swing.JLabel();
        txthireDate = new ObservingTextField();

        setBackground(new java.awt.Color(0, 153, 153));
        setEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblswan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblswan.setForeground(new java.awt.Color(255, 255, 255));
        lblswan.setText("Welcome To SWAN Network");
        add(lblswan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 230, 50));

        lblFirstName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("<html>Email <font color = red>*</font></html>");
        add(lblFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, 20));

        lblFirstName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFirstName1.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName1.setText("<html>First Name <font color = red>*</font></html>");
        add(lblFirstName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        lblFirstName2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFirstName2.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName2.setText("<html>Last Name <font color = red>*</font></html>");
        add(lblFirstName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        lblFirstName3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFirstName3.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName3.setText("<html>Gender <font color = red>*</font></html>");
        add(lblFirstName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, 20));

        lblFirstName4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFirstName4.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName4.setText("<html>Date of Birth <font color = red>*</font></html>");
        add(lblFirstName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 20));

        lblFirstName5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFirstName5.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName5.setText("<html>Phone <font color = red>*</font></html>");
        add(lblFirstName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, 20));

        radMale.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radMale.setForeground(new java.awt.Color(255, 255, 255));
        radMale.setSelected(true);
        radMale.setText("Male");
        radMale.setContentAreaFilled(false);
        radMale.setEnabled(false);
        add(radMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        radFemale.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        radFemale.setForeground(new java.awt.Color(255, 255, 255));
        radFemale.setText("Female");
        radFemale.setContentAreaFilled(false);
        radFemale.setEnabled(false);
        add(radFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, -1, -1));

        txtPhone.setEnabled(false);
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 140, 30));

        txtFirstName.setEnabled(false);
        add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 140, 30));

        txtDOB.setEnabled(false);
        add(txtDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 140, 30));

        txtEmail.setEnabled(false);
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 140, 30));

        txtLastName1.setEnabled(false);
        add(txtLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 140, 30));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        lblFirstName7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFirstName7.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName7.setText("Address");
        add(lblFirstName7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, 30));

        lblLocation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblLocation.setText("Location");
        add(lblLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, 30));

        txtLocation.setEnabled(false);
        add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 140, 30));

        lblMaritalstatus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMaritalstatus.setForeground(new java.awt.Color(255, 255, 255));
        lblMaritalstatus.setText("Marital Status");
        add(lblMaritalstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, 30));

        lblssn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblssn.setForeground(new java.awt.Color(255, 255, 255));
        lblssn.setText("<html>SSN <font color = red>*</font></html>");
        add(lblssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, 30));

        txtSSN.setEnabled(false);
        add(txtSSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 140, 30));

        lblPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/PersonIcon.png"))); // NOI18N
        add(lblPicture, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 210, 170));

        txtAddress.setEnabled(false);
        add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 140, 30));

        chkMarried.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        chkMarried.setForeground(new java.awt.Color(255, 255, 255));
        chkMarried.setText(" Married");
        chkMarried.setEnabled(false);
        chkMarried.setOpaque(false);
        add(chkMarried, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 140, 30));

        lblhireDate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblhireDate.setForeground(new java.awt.Color(255, 255, 255));
        lblhireDate.setText("<html>Hire Date <font color = red>*</font></html>");
        add(lblhireDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, 30));

        txthireDate.setEnabled(false);
        add(txthireDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
            userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        

    
    }//GEN-LAST:event_btnBackActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JCheckBox chkMarried;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFirstName1;
    private javax.swing.JLabel lblFirstName2;
    private javax.swing.JLabel lblFirstName3;
    private javax.swing.JLabel lblFirstName4;
    private javax.swing.JLabel lblFirstName5;
    private javax.swing.JLabel lblFirstName7;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblMaritalstatus;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblhireDate;
    private javax.swing.JLabel lblssn;
    private javax.swing.JLabel lblswan;
    private javax.swing.JRadioButton radFemale;
    private javax.swing.JRadioButton radMale;
    private javax.swing.JTextField txtAddress;
    private ObservingTextField txtDOB;
    /*
    private javax.swing.JTextField txtDOB;
    */
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName1;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtSSN;
    private ObservingTextField txthireDate;
    /*
    private javax.swing.JTextField txthireDate;
    */
    // End of variables declaration//GEN-END:variables

   
}
