/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SupportOrganizationAdmin.Report;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.SupportOrganization;
import Business.WorkQueue.SupportWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Jiya
 */
public class SupportTicketsStatusJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SupportTicketsStatusJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
     DefaultCategoryDataset bChartTicket;
     
    public SupportTicketsStatusJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
          bChartTicket = new DefaultCategoryDataset();
        populateChart();
    }
    public void populateChart()
    {
        int i = 0;
        int j = 0;
        int k = 0;
        int l = 0;
        int m = 0;
        for(Organization o : enterprise.getOrganizationDirectory().getOrganizationList())
        {
            if(o instanceof SupportOrganization)
            {
                    for(WorkRequest wr : o.getWorkQueue().getWorkRequestList())
                    {
                        if(wr instanceof SupportWorkRequest)
                        {
                          if(wr.getStatus().equalsIgnoreCase("Resolved"))
                          {
                              i++;
                          }
                          else if(wr.getStatus().equalsIgnoreCase("Returned"))
                          {
                              j++;
                          }
                          else if(wr.getStatus().equalsIgnoreCase("Pending Request"))
                          {
                              k++;
                          }
                          else if(wr.getStatus().equalsIgnoreCase("Open"))
                          {
                              l++;
                          }
                          else if(wr.getStatus().equalsIgnoreCase("Work in Progress"))
                          {
                              m++;
                          }
                       }
                    }
                }
            }
        bChartTicket.setValue(l, "Tickets", "Open");
         bChartTicket.setValue(k, "Tickets", "Pending Request");
         bChartTicket.setValue(m, "Tickets", "Work in Progress");
         bChartTicket.setValue(i, "Tickets", "Resolved");
         bChartTicket.setValue(j, "Tickets", "Returned");
         
         PopulateChart(bChartTicket,"Tickets");
         
    }
 public void PopulateChart(DefaultCategoryDataset bChart ,String yaxis)
    {
        
        
        JFreeChart barChart = ChartFactory.createBarChart(yaxis,"","", bChart,PlotOrientation.VERTICAL,true,true,false);
        CategoryPlot catChart = barChart.getCategoryPlot();
        CategoryAxis xaxis = (CategoryAxis) catChart.getDomainAxis();
        xaxis.setCategoryLabelPositions(CategoryLabelPositions.UP_45);
        BarRenderer b = (BarRenderer)catChart.getRenderer();
       // ItemLabelPosition(ItemLabelAnchor.OUTSIDE3, TextAnchor.CENTER, TextAnchor.CENTER, 90);
        b.setMaximumBarWidth(0.10);
        
        catChart.setRangeGridlinePaint(Color.WHITE);
        ChartPanel barPanel = new ChartPanel(barChart);
        
        ticketJPanel.removeAll();
        ticketJPanel.add(barPanel,BorderLayout.CENTER);
        ticketJPanel.validate();
       
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ticketJPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tickets Count");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 320, 40));

        ticketJPanel.setBackground(new java.awt.Color(0, 153, 153));
        ticketJPanel.setLayout(new java.awt.BorderLayout());
        add(ticketJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 520, 310));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel ticketJPanel;
    // End of variables declaration//GEN-END:variables
}
