/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.EnterpriseAdmin;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import Business.Validate;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jiya
 */
public class ManageOrganizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrganizationJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    SimpleDateFormat sdf;
    public ManageOrganizationJPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise=enterprise;
        sdf = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss a");
        AddOrganizationJPanel.setVisible(false);
     populateTable();
        populateCombo();
    }
    
    private void populateCombo(){
        cmbOrganizationType.removeAllItems();
        
        if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.Hospital))
        {
            
            cmbOrganizationType.addItem(Type.Admin);
            cmbOrganizationType.addItem(Type.Nurse);
            cmbOrganizationType.addItem(Type.Doctor);
            cmbOrganizationType.addItem(Type.Receptionist);
            cmbOrganizationType.addItem(Type.Patient);
        }
        else if(enterprise.getEnterpriseType().equals(Enterprise.EnterpriseType.SupportCenter))
        {
            cmbOrganizationType.addItem(Type.SupportAdmin);
            cmbOrganizationType.addItem(Type.SOC);
            cmbOrganizationType.addItem(Type.PatientSupport);
            cmbOrganizationType.addItem(Type.IT);
            cmbOrganizationType.addItem(Type.Billing);
            cmbOrganizationType.addItem(Type.Policy);
        }
        
        
    }

    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) tblOrganization.getModel();
       
        model.setRowCount(0);
        
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            Object[] row = new Object[5];
            row[0] = organization.getOrganizationID();
            row[1] = organization;
            row[2] = sdf.format(organization.getCreatedOn());
            if(organization.getModifiedOn() == null)
            {
                row[3] = "";
            }
            else
            {
                row[3] = sdf.format(organization.getModifiedOn());
            }
            if(organization.isStatus())
                row[4] = "Active";
            else
                row[4] ="InActive";

            
            model.addRow(row);
        }
         tblOrganization.setAutoResizeMode(tblOrganization.AUTO_RESIZE_ALL_COLUMNS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblswan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrganization = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        btnAddOrganization = new javax.swing.JButton();
        btnViewEmployeeDirectory1 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        AddOrganizationJPanel = new javax.swing.JPanel();
        lblAddOrganization = new javax.swing.JLabel();
        lblEnterpriseName = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnUpdateSave = new javax.swing.JButton();
        txtEnterpriseName = new javax.swing.JTextField();
        lblNetworkName2 = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        cmbOrganizationType = new javax.swing.JComboBox();
        lblOrganizationType = new javax.swing.JLabel();
        lblOrganizationName = new javax.swing.JLabel();
        txtOrganizationName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblswan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblswan.setForeground(new java.awt.Color(255, 255, 255));
        lblswan.setText("Manage Organization");
        add(lblswan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 230, 50));

        tblOrganization.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organization Id", "Organization Name", "Created On", "Modified On", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrganization);
        if (tblOrganization.getColumnModel().getColumnCount() > 0) {
            tblOrganization.getColumnModel().getColumn(0).setResizable(false);
            tblOrganization.getColumnModel().getColumn(1).setResizable(false);
            tblOrganization.getColumnModel().getColumn(2).setResizable(false);
            tblOrganization.getColumnModel().getColumn(3).setResizable(false);
            tblOrganization.getColumnModel().getColumn(4).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 80, 710, 110));

        btnDelete.setBackground(new java.awt.Color(255, 102, 102));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Organization");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 200, 30));

        btnAddOrganization.setBackground(new java.awt.Color(255, 102, 102));
        btnAddOrganization.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAddOrganization.setForeground(new java.awt.Color(255, 255, 255));
        btnAddOrganization.setText("Add Organization");
        btnAddOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrganizationActionPerformed(evt);
            }
        });
        add(btnAddOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 200, 30));

        btnViewEmployeeDirectory1.setBackground(new java.awt.Color(255, 102, 102));
        btnViewEmployeeDirectory1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnViewEmployeeDirectory1.setForeground(new java.awt.Color(255, 255, 255));
        btnViewEmployeeDirectory1.setText("View Organization Details");
        btnViewEmployeeDirectory1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewEmployeeDirectory1ActionPerformed(evt);
            }
        });
        add(btnViewEmployeeDirectory1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 210, 30));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 40));

        AddOrganizationJPanel.setOpaque(false);
        AddOrganizationJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAddOrganization.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAddOrganization.setForeground(new java.awt.Color(255, 255, 255));
        lblAddOrganization.setText("Organization Details");
        AddOrganizationJPanel.add(lblAddOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 140, -1));

        lblEnterpriseName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEnterpriseName.setForeground(new java.awt.Color(255, 255, 255));
        lblEnterpriseName.setText("<html>Enterprise Name <font color = red>*</font></html>");
        AddOrganizationJPanel.add(lblEnterpriseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        btnSave.setBackground(new java.awt.Color(255, 102, 102));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        AddOrganizationJPanel.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        btnUpdate.setBackground(new java.awt.Color(255, 102, 102));
        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Edit");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        AddOrganizationJPanel.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 60, -1));

        btnUpdateSave.setBackground(new java.awt.Color(255, 102, 102));
        btnUpdateSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateSave.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateSave.setText("Save");
        btnUpdateSave.setEnabled(false);
        btnUpdateSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateSaveActionPerformed(evt);
            }
        });
        AddOrganizationJPanel.add(btnUpdateSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        txtEnterpriseName.setEnabled(false);
        AddOrganizationJPanel.add(txtEnterpriseName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 160, 30));

        lblNetworkName2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNetworkName2.setForeground(new java.awt.Color(255, 255, 255));
        lblNetworkName2.setText("<html>Location <font color = red>*</font></html>");
        AddOrganizationJPanel.add(lblNetworkName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, 30));

        txtLocation.setEnabled(false);
        AddOrganizationJPanel.add(txtLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 160, 30));

        cmbOrganizationType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrganizationTypeActionPerformed(evt);
            }
        });
        AddOrganizationJPanel.add(cmbOrganizationType, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 160, 30));

        lblOrganizationType.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOrganizationType.setForeground(new java.awt.Color(255, 255, 255));
        lblOrganizationType.setText("<html>Organization Type <font color = red>*</font></html>");
        AddOrganizationJPanel.add(lblOrganizationType, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        lblOrganizationName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblOrganizationName.setForeground(new java.awt.Color(255, 255, 255));
        lblOrganizationName.setText("<html>Organization Name <font color = red>*</font></html>");
        AddOrganizationJPanel.add(lblOrganizationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, 30));

        txtOrganizationName.setEnabled(false);
        AddOrganizationJPanel.add(txtOrganizationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 160, 30));

        add(AddOrganizationJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 480, 300));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

        String organizationLoc = txtLocation.getText().trim();
        String organizationName = txtOrganizationName.getText().trim();
        boolean boolorganizationLoc = Validate.isString(organizationLoc);
        boolean boolorganizationName = Validate.isalphanumeric(organizationName);
        if( !organizationLoc.isEmpty() && !organizationName.isEmpty() && cmbOrganizationType.getSelectedItem() != null )
        {
            if(boolorganizationLoc && boolorganizationName)
            {
                txtLocation.setBackground(Color.WHITE);
                txtOrganizationName.setBackground(Color.WHITE);
              //  System.out.println("type organization"+cmbOrganizationType.getSelectedItem());
                Organization org = enterprise.getOrganizationDirectory().createOrganization(organizationName,(Type)cmbOrganizationType.getSelectedItem());
                org.setCreatedOn(new Date());
                org.setLocation(organizationLoc);
                org.setStatus(true);
                JOptionPane.showMessageDialog(null,"Organization added succesfully","Succes",JOptionPane.INFORMATION_MESSAGE);
             //   txtOrganizationName1.setText("");
                txtLocation.setText("");
                populateTable();
                AddOrganizationJPanel.setVisible(false);
            }
            else
            {

                if(!boolorganizationLoc)
                {
                    txtLocation.setBackground(Color.red);
                }
                JOptionPane.showMessageDialog(null,"Invalid data","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Fields cannot be empty","Information",JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        btnUpdateSave.setEnabled(true);
        btnUpdate.setEnabled(false);
        txtEnterpriseName.setEnabled(false);
        txtLocation.setEnabled(true);
        txtOrganizationName.setEnabled(true);
        cmbOrganizationType.setEnabled(false);
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUpdateSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateSaveActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblOrganization.getSelectedRow();

        Organization org = (Organization) tblOrganization.getValueAt(selectedrow, 1);
         
        String organizationLoc = txtLocation.getText().trim();
        String organizationName = txtOrganizationName.getText().trim();
        boolean boolorganizationLoc = Validate.isString(organizationLoc);
        boolean boolorganizationName = Validate.isString(organizationName);
        if(!organizationLoc.isEmpty() && !organizationName.isEmpty() && cmbOrganizationType.getSelectedItem() != null )
        {
            if(boolorganizationLoc && boolorganizationName)
            {
               txtLocation.setBackground(Color.WHITE);
               txtOrganizationName.setBackground(Color.WHITE);
                ;

                
                org.setLocation(organizationLoc);
                org.setName(organizationName);
                org.setModifiedOn(new Date());
                JOptionPane.showMessageDialog(null,"Organization details updated successfully","Success",JOptionPane.INFORMATION_MESSAGE);
                populateTable();
                AddOrganizationJPanel.setVisible(false);
            }
            else
            {
                if(!boolorganizationLoc)
                {
                    txtLocation.setBackground(Color.red);

                }
                else
                {
                    txtLocation.setBackground(Color.WHITE);
                }
                if(!boolorganizationName)
                {
                    txtOrganizationName.setBackground(Color.red);

                }
                else
                {
                    txtOrganizationName.setBackground(Color.WHITE);
                }

                JOptionPane.showMessageDialog(null,"Invalid data","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Fields cannot be empty","Warning",2);
        }
    }//GEN-LAST:event_btnUpdateSaveActionPerformed

    private void btnAddOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddOrganizationActionPerformed
        // TODO add your handling code here:
        AddOrganizationJPanel.setVisible(true);
        txtEnterpriseName.setText(enterprise.getName());
        populateCombo();
        txtLocation.setText("");
        txtOrganizationName.setText("");
        cmbOrganizationType.setEnabled(true);
        txtOrganizationName.setEnabled(true);
        txtLocation.setEnabled(true);
        btnSave.setVisible(true);
        btnSave.setEnabled(true);
        btnUpdate.setVisible(false);
        btnUpdateSave.setVisible(false);
        
    }//GEN-LAST:event_btnAddOrganizationActionPerformed

    private void btnViewEmployeeDirectory1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewEmployeeDirectory1ActionPerformed
        // TODO add your handling code here:
        int selectedrow = tblOrganization.getSelectedRow();
        if(selectedrow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row to edit","Information",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        Organization o = (Organization) tblOrganization.getValueAt(selectedrow,1);
        
        AddOrganizationJPanel.setVisible(true);
        txtEnterpriseName.setEnabled(false);
        txtEnterpriseName.setText(enterprise.getName());
        txtLocation.setEnabled(false);
        txtOrganizationName.setEnabled(false);
        txtLocation.setText(o.getLocation());
        txtOrganizationName.setText(o.getName());
        cmbOrganizationType.setSelectedItem(o.getOrganizationType());
        cmbOrganizationType.setEnabled(false);

        btnUpdate.setVisible(true);
        btnUpdate.setEnabled(true);
        btnSave.setVisible(false);
        btnUpdateSave.setVisible(true);
        btnUpdateSave.setEnabled(false);
    }//GEN-LAST:event_btnViewEmployeeDirectory1ActionPerformed

    private void cmbOrganizationTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrganizationTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrganizationTypeActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
          int selectedrow = tblOrganization.getSelectedRow();
        if(selectedrow < 0)
        {
            JOptionPane.showMessageDialog(null,"Please select any row to delete","Information",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
       
        Organization org = (Organization) tblOrganization.getValueAt(selectedrow, 1);
        enterprise.getOrganizationDirectory().deleteEnterprise(org);
        JOptionPane.showMessageDialog(null,"Organization deleted successfully","Success",JOptionPane.INFORMATION_MESSAGE);
        populateTable();
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddOrganizationJPanel;
    private javax.swing.JButton btnAddOrganization;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpdateSave;
    private javax.swing.JButton btnViewEmployeeDirectory1;
    private javax.swing.JComboBox cmbOrganizationType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddOrganization;
    private javax.swing.JLabel lblEnterpriseName;
    private javax.swing.JLabel lblNetworkName2;
    private javax.swing.JLabel lblOrganizationName;
    private javax.swing.JLabel lblOrganizationType;
    private javax.swing.JLabel lblswan;
    private javax.swing.JTable tblOrganization;
    private javax.swing.JTextField txtEnterpriseName;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtOrganizationName;
    // End of variables declaration//GEN-END:variables
}
